### ISSUE TITLE
Add QuiltMC support for FabricMC servers

### ISSUE THREAD

**Issue by s3nkwr** [Skidamek/AutoModpack#100]
**Is your feature request related to a problem? Please describe.**
I'm making a FabricMC server and QuiltMC players can't load the modpack.
And when I migrated the server to QuiltMC the Fabric players couldn't load it.

**Describe the solution you'd like**
Make an option that will enable QuiltMC client support on FabricMC server.
And vice versa. FabricMC clients on QuiltMC Servers

**Describe alternatives you've considered**
Custom launcher or Modpacks.

**Additional context**
No additional. Only support QuiltMC on FabricMC servers

**Comment by Skidamek** [comment]
Well i made it like that to prevent incompatibilities between these two mod loaders because they are...
If you making quilt server players also should use quilt loader and vice versa, right?

**Comment by s3nkwr** [comment]
I use only QuiltMC server side mods.

**Comment by Skidamek** [comment]
ok you got me xD

**Comment by s3nkwr** [comment]
can you build for 1.19.3?

**Comment by Skidamek** [comment]
Oh that's done already in 3.1.0 and up
