### ISSUE TITLE
Error while unzipping due to file with a user-mapped section open.

### ISSUE THREAD

**Issue by JLUsr** [Skidamek/AutoModpack#101]
### This issue was made with the hope to open dialogue with other users who might be having similar issues to find the cause and potentially a solution. This issue is extremely difficult for the average user to reproduce considering there is no information as to why this occurred at this time.

**Describe [the bug](https://gist.github.com/JLUsr/9c0bbea67b8c5cbbe5bd916c9966ff39)**
Occasionally when updating the modpack (either during PreLaunch or on an attempt to connect to the server) the client will encounter a strange error while the modpack is unzipping. The result is that the modpack does not finish transferring files to the designated folders which causes a discrepancy between the modpack.zip and the mods the client actually has.

**To Reproduce**
Unknown at this time.
Once it occurs it happens as follows...
1. Download modpack through AutoModpack.
2. On the server side add or remove a mod from the modpack and restart the server.
3. On the client side update the modpack either through PreLaunch or by attempting to connect to the server.
4. This is where the issue might occur. Sometimes it doesn't and sometimes it does, if it doesn't happen it might occur during the next modpack update.

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - AutoModpack 2.4.1.0 and 3.0.3 (Including the most recent [test build](https://github.com/Skidamek/AutoModpack/actions/runs/4216974007)) for Minecraft 1.19.2  | Tested using PrismLauncher & Technic

**Additional context**
I don't know if this is actually an AutoModpack issue or if it has something to do with the source zip; however, It happens occasionally after a few modpack updates and can prevent the unzipping process from actually completing. Since the modpack size matches the server's modpack size it won't attempt to redownload/retransfer the mods to the correct directory which, in turn, causes that specific update to fail on the client side.

This is an issue I haven't had until recently, I was able to confirm that other players/clients are having the same issue. I was not able to identify why this issue occurred, how to force it to reoccur, or how to stop it. The mods being referenced change and are semi-random. I can testify that the mods themselves are not directly incompatible considering I started seeing this issue about 2 days ago and some of the referenced mods have been present for around 1 month by now.

**Client & Server log**
See [this gist](https://gist.github.com/JLUsr/9c0bbea67b8c5cbbe5bd916c9966ff39).

**Comment by Skidamek** [comment]
Thanks for long report. However this can't happen on automodpack v3 which doesn't even contains unzipper class. It doesn't unzip anything now. That's 2.4.1 bug.

**Comment by Skidamek** [comment]
Could you also send log with this bug from 3.0.3?

**Comment by Skidamek** [comment]
Hm interesting, i don't know if i can do anything with that except for mark it as incompatible.
Thanks for the great amount of information really appreciate that!

**Comment by Skidamek** [comment]
Added as breaks in 3.1.0 beta (only 1.19.2 at the moment)
