### ISSUE TITLE
Relauncher won't work on either linux or windows

### ISSUE THREAD

**Issue by MojoReach** [Skidamek/AutoModpack#103]
**Describe the bug**
not loading on relaunch. The issue is that the checking, downloading, and updating mods from the server are looping and the game is not reluanching. this is not an os issue it is happening with my friend

The bug is where when the client logs in the server says to restart but when it restarts it asks the question again

**To Reproduce**
1. connect to server
2. download mods
3. restart

**Expected behavior**
I expected it to check thorugh all the mods then load minecraft but it never gets to that part

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - 3.0.3
 - Latest fabric
 - 1.19.2

**Additional context**
I am using linux ubuntu 22.04
my friend is using windows 10

**Client & Server log**
Log from ./logs/latest.log (If you scared of ip leak, please dm me logs on discord Skidam#8666)
My Friend's: <html>at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:146)<br>at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:146)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:210)<br>at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)<br>at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>
[10:30 PM]
<html>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:263)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:212)<br>at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)<br>at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)<br>at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)<br>at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)<br>at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)<br>at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)</html>
[10:30 PM]
<html>at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)<br>at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)<br>at java.base/java.util.zip.ZipFile$Source.&lt;init&gt;(ZipFile.java:1315)<br>at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)<br>at java.base/java.util.zip.ZipFile$CleanableResource.&lt;init&gt;(ZipFile.java:709)<br>at java.base/java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:243)<br>at java.base/java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:172)<br>at java.base/java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:186)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:284)<br>at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:253)<br>... 7 more</html>

Mine ([2023-02-24-7.log](https://github.com/Skidamek/AutoModpack/files/10830397/2023-02-24-7.log))

**Comment by TheRealM18** [comment]
I have the same issue, and my workaround was add the deletedmods folder in the mods folder.  This will make it launch.  It seems to only happen when it has a copy of it in the main mods folder, and will not allow you to have more then one copy of it to launch.  as the mod relaunches the instance into its own folder structure, it seems to be missing a guarantee Fabric-API and for me the required dependency for running it in velocity mode.

A simple fix is to allow mods that are in the default folder copied over, and have or have certain ones forced to stay.

**Comment by Skidamek** [comment]
Fixed in 3.1.0 beta (only 1.19.2 at the moment)
