### ISSUE TITLE
Fabrication's 'features.ini' causes update loop on 3.0.3

### ISSUE THREAD

**Issue by JLUsr** [Skidamek/AutoModpack#104]
When using automodpack-3.0.3-1.19.2 (Minecraft 1.19.2 Quilt and Fabric was tested) ([the latest commit](https://github.com/Skidamek/AutoModpack/commit/656ee55848b3e0e926a267685d8f7d284123219b)) the config file at `/config/fabrication/features.ini` which is used by [Fabrication](https://modrinth.com/mod/fabrication) will cause an update loop if it is included in the modpack.

**Comment by Skidamek** [comment]
I guess not only that file, there is bigger problem that i can't understand why it is happening. I mean really the checksums of some random files are sometimes just wrong... Could you send the log from client while it loops?

**Comment by Skidamek** [comment]
If you really want to, you can try new build from latest commit but its not the best... For sure it has bugs and doesn't look too great but at least it should mostly work now
