### ISSUE TITLE
Stuck on "Install/Update modpack to join" 3.0.3-1.19.2

### ISSUE THREAD

**Issue by ginsm** [Skidamek/AutoModpack#106]
Describe the bug
-
**What I'm doing on the server:**
I'm hosting my modpack on my server with this config: [automodpack-server.json](https://pastebin.com/T3MddJbV).

**What I'm doing on the client:**
I'm creating a new CurseForge instance, downloading AutoModpack, creating the client config manually ([automodpack-client.json](https://pastebin.com/iZhmwgJF)), launching the instance, connecting to the server, downloading the modpack, and restarting afterwards.

After the restart I can't seem to connect -- it simply states that it `Failed to connect to the server` and provides `[AutoModPack] Install/Update modpack to join` as a reason. There's no download button or anything of the sort showing up when I reach this screen.

It seems to think there's a modpack update, but nothing actually seems to change from what I can tell (according to the provided logs below)? I've tried restarting the client in succession and trying to connect but no luck.. and I've tried to simply connect in succession as well, but again, no luck.

Expected behavior
-
It should connect to the server from what I can tell.

AutoModpack and Minecraft Version
-
**Minecraft:** `1.19.2`
**Fabric Loader:** `0.14.14`
**Fabric API:** `0.75.1-1.19.2`
**AutoModpack:** `3.0.3-1.19.2`

Additional Context
-
I'm probably just misusing the mod somehow. I'm not sure if this is really a "bug" per-se and more-so just me needing help to see what I'm doing wrong. :D

Client & Server log
-
 I can provide full logs over Discord if you'd like but for now:

Here are snippets of what's happening when I try to connect: [Client](https://pastebin.com/4JmbXBpz), [Server](https://pastebin.com/zNVzw4mU).

And here's an image of the screen after trying to connect: https://i.imgur.com/BbtjZ1D.png.

There wasn't anything of note in terms of initializing AutoModpack, it seems to be doing so without issue, but here's snippets of that as well: [Client](https://pastebin.com/ufy2F2PW), [Server](https://pastebin.com/0KcWSr2P).

**Comment by ginsm** [comment]
The only thing I could think of is maybe it's having an issue with [Paxi](https://modrinth.com/mod/paxi)? It seemed to have issues with [YOSBR](https://modrinth.com/mod/yosbr) so I removed that from the pack.. your mod essentially allows for the same functionality anyway (with editable files).

**Comment by Skidamek** [comment]
I see the issue and think i fixed it in dev could you try this dev build from GitHub actions? https://github.com/Skidamek/AutoModpack/suites/11315331477/artifacts/581028054

**Comment by Skidamek** [comment]
sus

**Comment by Skidamek** [comment]
Could you try this build please? https://github.com/Skidamek/AutoModpack/suites/11436238178/artifacts/589605810

**Comment by ginsm** [comment]
Sure! It seems to be experiencing the same issue, here's everything again:

[automodpack-server.json](https://pastebin.com/hibwFTM7)
[server log](https://pastebin.com/3UDmgqzM)
[client log](https://pastebin.com/7bwJs18k)

**Comment by Skidamek** [comment]
Oh right that could be the issue

**Comment by ginsm** [comment]
On a side note, a couple things with the build you shared with me seem to not be working:

1. It'll say it's syncing when running `automodpack generate` with [this config](https://pastebin.com/hibwFTM7) but when I check it doesn't actually change any of the files in `automodpack/host-modpack`. The server is being ran on `Debian 11 (Bullseye)` if that matters any.
2. And, I'm not sure how this mod typically handles it, but if I delete a mod from the pack it'll still remain on the client. So, when I update a mod, the previous version ends up staying as well.

I know it's not really meant to be used as it's a dev build and still being worked on but figured I'd mention it just the same. I can share my modpack with you if you'd like or test any future builds; just let me know & thanks for the mod -- it's pretty cool. :grin:

**Comment by Skidamek** [comment]
Ok so 
1. Don't look at /automodpack/host-modpack/ look what's in the /automodpack/host-modpack/modpack-content.json

2. Thanks for remaining i am working on it, since i changed that mods are loading from default Minecraft directory many things like this need to change logic 

Thank you! :)

**Comment by Skidamek** [comment]
Fixed in 3.1.0 beta (only 1.19.2 at the moment)
