### ISSUE TITLE
AutoModpack mod fails to delete the outdated files/mods

### ISSUE THREAD

**Issue by Manic137** [Skidamek/AutoModpack#111]
Changing an existing mod to an updated one causes the client to crash with an error after an update of the modpack, AutoModpack mod fails to delete the original file

1. Stop the server
2. Delete the outdated mod
3. Add the updated mod
4. Start the server to generate the new modpack
5. Join with a client to update existing modpack
6. You will get an error when you restart the client
7. Inspecting the mod folder on client shows that the outdated mod is now 0KB, meaning an attempt was made to delete but it failed

**Expected behavior**
Expected the mod to delete the outdated mod and not crash the client

**Screenshots**
![image](https://user-images.githubusercontent.com/88038453/232288872-3549daee-3393-46fd-bc6b-dd85a417be33.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - Fabric 1.19.4
 - AutoModpack 3.2.0

**Additional context**
Deleting the 0KB file will fix the issue, thus confirming that AutoModpack can't seem to delete files

**Client & Server log**
Don't think a log is needed in this instance, but if you require it, I will pm it to you

**Comment by Skidamek** [comment]
Yeah, yesterday i started server for my friends and they noticed that. I didn't before because somehow it works without issues on Linux. I need to fix that fast, thanks for reporting though, more motivation to do it so :)

**Comment by Manic137** [comment]
> Yeah, yesterday i started server for my friends and they noticed that. I didn't before because somehow it works without issues on Linux. I need to fix that fast, thanks for reporting though, more motivation to do it so :)

Pog, my server is on Ubuntu, but pretty sure most people I know play on Win10

**Comment by Skidamek** [comment]
Publishing 3.2.1 in few minutes
