### ISSUE TITLE
Cannot invoke "String.equals(Object)" because "serverSHA1" is null

### ISSUE THREAD

**Issue by Guerdi** [Skidamek/AutoModpack#117]
In version 3.3.0 of AutoModpack, when connecting the server this message is displayed and the files are not applied.
They are however all downloaded in the "automodpack\modpacks\IPSERVER\" folder but are not then moved to the right places.

**Screenshots**

![image](https://github.com/Skidamek/AutoModpack/assets/14162145/ab468c68-c4a5-4f1a-ac29-cca4814dc921)

**AutoModpack and Minecraft Version you are using (please complete the following information):**

**Minecraft** : `1.19`
**Quilt Loader** : `1.18.10`
**AutoModpack** : `3.3.0`

**Client & Server log**
Here are the client logs, the server basically says just "lost connection: [AutoModpack] Install/Update modpack to join"
[latest.log](https://github.com/Skidamek/AutoModpack/files/11457150/latest.log)

**Comment by Skidamek** [comment]
Are you sure you have also automodpack 3.3.0 on server? if so try regenerating modpack by executing /automodpack generate
If it won't help please send log from server and zipped automodpack directory.
