### ISSUE TITLE
Problem after Updating Mods from Modpack "PreLaunch"

### ISSUE THREAD

**Issue by suerion** [Skidamek/AutoModpack#118]
**Describe the bug**
Hey, i had added only Updates on our Server, now it does not start anymore.
[latest.log](https://github.com/Skidamek/AutoModpack/files/11471441/latest.log)

**To Reproduce**
1. Stopped the Server
1. Updated 4 Mods and added 1 mod.
2. Changed the config of the Automodpack (only added an exluded sync file)
3. Started the server again

**Expected behavior**
Server should start without Problems

**AutoModpack and Minecraft Version you are using (please complete the following information):**
Auto Modpack 3.3.0
Minecraft 1.19.2
Fabric 0.14.19

**Comment by Skidamek** [comment]
Remove automodpack and check if it crashes without it

**Comment by suerion** [comment]
It crash without Automodpack, don't know why....

had also disabled other Mods. from the errors... Does Fabric change something on there side?

**Comment by Skidamek** [comment]
No, then probably some mod that you added / updated crashes. I am closing this issue.

**Comment by suerion** [comment]
I give Info, that MCDW is the problem
