### ISSUE TITLE
CommandRegistrationCallback

### ISSUE THREAD

**Issue by creggy** [Skidamek/AutoModpack#124]
java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/command/v2/CommandRegistrationCallback.

Get this error when launching, have latest 1.19.2 fabric and latest of your mod but getting that error
 -  Version 1.19.2 on server

Error shows on console when trying to start server

[crash-2023-06-08_06.23.30-fml.txt](https://github.com/Skidamek/AutoModpack/files/11684752/crash-2023-06-08_06.23.30-fml.txt)

**Comment by Skidamek** [comment]
This is fabric/quilt mod. Forge is not yet supported.

**Comment by creggy** [comment]
even though i have the fabric api downloaded?

**Comment by Skidamek** [comment]
Even if you have it downloaded, it doesn't load into forge, fabric API is also fabric mod. So no, it will not work. However this summer i want to finnaly complete the forge port, stay tuned! :)
