### ISSUE TITLE
What about a Forge release? 

### ISSUE THREAD

**Issue by hazard1nc** [Skidamek/AutoModpack#128]
This is a very much needed thing for all the people, and all the mod loading platforms! I wish I had half the talent you all do, I wanna be able to port it myself, but I'm not good at programming, yet anyway. I love this and really need something like it for my family server, they don't understand how to do all the mods, and they don't have the patience to learn.  So, I'm stuck for hours downloading everything on a hotspot tether from my phone, you have no idea how much it sucks! This would be handy for them, I could just update the mods on the server, and make sure to set them up for auto mod updates!

Please think about it, or someone please port it over! We really require this for many servers. I was thinking to upload it to one of the mod pack launchers, but I don't know how to do any of that and this would be way easier! 

I gave you the highest rating I could for this, It works well on fabric, the tests went well! thought you should know, all of you that put in  that time for this project, thank you all for this amazing tool! just, can we please port it over to others? even if it's just forge

**Comment by EzequielDM** [comment]
Will comment here to show my support on this suggestion, I really would love to have this mod on Forge to manage servers for bigger modpacks. Sadly not all mods are ported to fabric nowadays so we're still stuck to Forge most of the time. Really looking forward to seeing the Forge port.
This mod is something I've been talking about for over 10 years now but never put the effort to create, finally it's here.

**Comment by Skidamek** [comment]
First forge build RELEASED! :DD
https://modrinth.com/mod/automodpack/version/SI0Y076R

**Comment by MrKashew** [comment]
@Skidamek I want to second OP, this mod is amazing and I'm so excited for the forge release - it perfectly fits my server's use case as well and there is no modpacker streamer that works on runtime like this one does
