### ISSUE TITLE
Crashing because of automatic update

### ISSUE THREAD

**Issue by Shrimplonex** [Skidamek/AutoModpack#129]
### Bug description

I have been using auto modpack perfectly fine for a little wwhile for my group of friends, using automodpack-3.3.1-1.20.jar on fabric. However today automodpack-mc1.20.1-fabric-3.3.2.jar released, and the current version of automodpack forces this new version into the mods folder, but doesnt remove the old one, and it just causes the game to continuously crash. In my honest opinion, the mod automatically updating itself should in no way even BE a feature, let alone something on automatically. 

The whole poitn of the mod is to be able to change the modpack in our server without having to tell everyone "alright go to the mods folder, remove this, drag this file in, now go on curse and search this in "add more content" but now because of a forced update, have to go in and do all of that anyways, hey go to mods delete this file install the new version etc etc because the game just crashes

### Steps to reproduce

fabric 1.20 
automodpack 3.3.1-1.20
click play
automatically installs 1.20.1-3.3.2
game crashes

### Expected behavior

to click play and have the modpack work as normal on the client and not be pushed to update the mod unless prompted by the server

### Minecraft version

1.20

### AutoModpack version

3.3.1 into 3.3.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
I am sorry, it definitely shouldn't happen, actually in this version fixed eventual issues with self-updating and deleting mods now its all should work way better. I bet you are using quilt mod loader right? it's frustrating... 
However if you want to, you can disable self-updating mod in config.

**Comment by Shrimplonex** [comment]
and now the updated version of automodpack isnt actually picking up all the mods in the server and updating to the pack. In fact there was less issues with the previous version

**Comment by Skidamek** [comment]
Holy cow! I just debuged it and my new auto-uploading script to modrinth broke it lol
I just fixed it

**Comment by Skidamek** [comment]
less issues?

**Comment by Shrimplonex** [comment]
Yeah with the previous versionbeing 3.3.1, everything was working smoothly, but now evenwith aclient with fresh install of 3.3.2 , it's missing updating some mods from a fresh client, whereas 3.3.1 was workign as intended. I'm doing another test really quick to see if the issue is on my end first

**Comment by Shrimplonex** [comment]
I'm not sure what's going on, because now even 3.3.1 of automodpack isnt working, it's saying it is downloading the mods in the screen, but then doesnt actually download them and put them into the mods folder of the client.  It is populating the "modpack-content.json" but not actually downloading anything. The server is set up properly with the correct config options and ports openned. And liek i said, it's detecting it, in game it's saying it's downloading it, it just isnt actually doing it

**Comment by Shrimplonex** [comment]
and now backdating to 3.3.1 automodpack causes the server to crash and not load up either, so it's kidna forced to use the updated one on the server end too

**Comment by Skidamek** [comment]
> I'm not sure what's going on, because now even 3.3.1 of automodpack isnt working, it's saying it is downloading the mods in the screen, but then doesnt actually download them and put them into the mods folder of the client. It is populating the "modpack-content.json" but not actually downloading anything. The server is set up properly with the correct config options and ports openned. And liek i said, it's detecting it, in game it's saying it's downloading it, it just isnt actually doing it
> 
> I guess now i'm not sure if it's related, however this hasnt been an issue until today when this update went live

Are you sure? Could you send log?

**Comment by Shrimplonex** [comment]
like are you wanting my latest.log of when it says it's downloading but isnt, or the latest.log of the game telling me i'm missing all the registries from all the mods even thought modpack-content.json is full

**Comment by Shrimplonex** [comment]
and is there any reason why now trying to use automodpack 3.3.1 in the server just crashes it? Is it the same thing th client is encountering, trying to force its own update to 3.3.2 and then crashing because of it? Is that actually intended?

**Comment by Skidamek** [comment]
How does it crashes? Yes, log would be really useful... i can't really help you other way

**Comment by Skidamek** [comment]
I just tested with fresh client and old client everything works perfectly fine on latest version

**Comment by Shrimplonex** [comment]
https://mcpaste.io/adbd8010c9d4db29 Starting line 443, crash upon trying to use automodpack 3.3.1 on server. 3.3.2 Server loads fine. I'll ge you client latest.log of trying to download the mods in a second

**Comment by Shrimplonex** [comment]
oh yeah that crash is also just the forced update i see that line now. I'll woork on getting you client log in one second.

**Comment by Skidamek** [comment]
could you manually update server to 3.3.2? It is broke because of 3.3.1 in 3.3.2 it is fixed

**Comment by Shrimplonex** [comment]
[latest.log](https://github.com/Skidamek/AutoModpack/files/11839319/latest.log)
Latest.log shows all the mods being downloade,d however automodpack/modpacks/myserverip/mods is empty aside from fabric api even though it says it downloaded them all. modpack-content.json however has all the mods in it

**Comment by Shrimplonex** [comment]
i had a zip file import for curseforge for when i made the pack, and obviously have since then added some. When loading, it says it's downloading them all, and then doesnt actualyl download them anywhere

**Comment by Skidamek** [comment]
> [latest.log](https://github.com/Skidamek/AutoModpack/files/11839319/latest.log) Latest.log shows all the mods being downloade,d however automodpack/modpacks/myserverip/mods is empty aside from fabric api even though it says it downloaded them all. modpack-content.json however has all the mods in it

Looks clean, what happens after restart? could you send another log with that?

**Comment by Shrimplonex** [comment]
[latest.log](https://github.com/Skidamek/AutoModpack/files/11839345/latest.log)
It's like it's saying it's downloading everything but it's just not. When trying to join after "success, restar to update!" or whatever it says, restarting still just had only fabric api and auto modpack, and nothing else.

**Comment by Shrimplonex** [comment]
C:\Users\myusername\curseforge\minecraft\Instances\313516546\automodpack\modpacks\serveriphidden-8004\mods  is still empty as well.

**Comment by Shrimplonex** [comment]
I'm attempting to do this of f a fresh install of fabric 1.20 and automodpack 3.3.2, and fabric api, nd nothing else. This is the results of that on my end

**Comment by Skidamek** [comment]
its so strange because it just works on my side, but what is different are our launchers.. Could you try on diffrent launcher than curseforge? its really the worst... Try e.g. prism or multimc or even vanilla

**Comment by Shrimplonex** [comment]
yeah but almost every other mod in the modpack requires fabric api to work as it is a f abric modpack. I can try starting without it though if you think that will matter. Just not sure why, 24 hours ago it worked perfectly fine, on curseforge, but now all of a sudden after the update, a fresh install wih just AMP , ***and*** the users who are completely up to date minus like 1 mod, any mod that amp says it downloaded, it didnt. I can' try wwith something other than curse but that really shouldnt be the solution, as again every user on my server is using curse, and up until this update everything was workign fine

**Comment by Skidamek** [comment]
fabric api should download automodpack from server's modpack just automodpack now doesn't require it as is. I understand i just want to check what is really wrong, because if it doesn't work because of curseforge then idk this company sucks

**Comment by Skidamek** [comment]
And why it worked before for you on curseforge.... no clue

**Comment by Shrimplonex** [comment]
Testing it with prism launcher on a fresh 1.20 fabric install with only automodpack.

**Comment by Shrimplonex** [comment]
Now it doesnt even pop up trying to say "Hey install the modpack" it just jumps right to not having the registries. Fresh install on 1.20 fabric with prism launcher it seemed like it just straight up didnt work

**Comment by Shrimplonex** [comment]
Same thing. Fresh install on prism with 1.20 fabric and 3.3.2, it says it is downloading the mods, goes through all the animations and stuff, then doesnt actually download anything.

**Comment by Skidamek** [comment]
alright i think i catched the issue....

**Comment by Shrimplonex** [comment]
Backdating server and client to 3.3.1 and disabling self updating to see if it works as intended with everything on 3.3.1

And oh? What does it look to be?

**Comment by Skidamek** [comment]
modpack-content generating optimization breaks it all i think

**Comment by Skidamek** [comment]
> Backdating server and client to 3.3.1 and disabling self updating to see if it works as intended with everything on 3.3.1
> 
> And oh? What does it look to be?

Could you first, try this new build, i hope this will fix it
[automodpack-mc1.20.1-fabric-3.3.2-SHAPSHOT.zip](https://github.com/Skidamek/AutoModpack/files/11839568/automodpack-mc1.20.1-fabric-3.3.2-SHAPSHOT.zip)

**Comment by Skidamek** [comment]
wait

**Comment by Skidamek** [comment]
[automodpack-mc1.20.1-fabric-3.3.3-SHAPSHOT.zip](https://github.com/Skidamek/AutoModpack/files/11839578/automodpack-mc1.20.1-fabric-3.3.3-SHAPSHOT.zip)

**Comment by Shrimplonex** [comment]
yah this works now

**Comment by Shrimplonex** [comment]
Whenever you publish this, i'll just have to have my users all manually go in to update automodpack and should hopefully resolve any issues

**Comment by Skidamek** [comment]
thank you for fast updates and reports i am gonna push this fast

**Comment by Shrimplonex** [comment]
game did just crash after the patch fro mthe server, but i think that had to do with my modpack more than the server

**Comment by Shrimplonex** [comment]
yep im logged in, it all works at intended now. I would still invite you to consider defaulting self-update to false though. I realized when doing a vanilla client with JUST automodpack, it pops up saying "hey automodpack is updated" however it seems like in actual modpacks or servers it just crashes instead. May be worth looking into in the future

**Comment by Shrimplonex** [comment]
[latest.log](https://github.com/Skidamek/AutoModpack/files/11839626/latest.log)
Here is log of trying to run the modpack with 3.3.1 installed, expected behavior if it is *going* to automatically update, is that it updates smoothly, however it just appears to crash unless manually updated.

**Comment by Skidamek** [comment]
that's yacl crash completely not related to automodpack, update yacl https://modrinth.com/mod/yacl/version/3.0.1+1.20-fabric

**Comment by Skidamek** [comment]
automodpack 3.3.3 released, thanks i am gonna close this.
