### ISSUE TITLE
Installation problems when connecting to the server for the first time

### ISSUE THREAD

**Issue by ajb3296** [Skidamek/AutoModpack#130]
### Bug description

If you try to connect to the server where the auto mod pack is applied for the first time, the auto mod pack detects that the mods have been downloaded, but the mod files are not downloaded on the client.

### Steps to reproduce

1. Attempting to connect to a server with AutoModPack applied

### Expected behavior

Users who try to connect to the server for the first time cannot connect

### Actual behavior

Users who try to connect to the server for the first time cannot connect

### Relevant logs

![image](https://github.com/Skidamek/AutoModpack/assets/33373557/d023ea54-bab3-484b-bd02-87bc2ebdd29a)

### Minecraft version & Mod Loader

1.19.2 Fabric

### Operating system

Macos 14.0 BETA 2, Windows11

### AutoModpack version

3.3.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Thanks, fixed in 3.3.4
