### ISSUE TITLE
Doesn't put mods in mods folder

### ISSUE THREAD

**Issue by Hexiph** [Skidamek/AutoModpack#132]
### Bug description

When i join my server all the mods will be installed fine, but once i restart the game none of the mods get put into the mods folder. All my config files are imported fine and the modpack-content file saves all the mods but no mods folder is created within the automodpack folder and no mods are applied to the game.

### Steps to reproduce

1. install automodpack-mc1.19.4-fabric-3.3.4
2. join modded server with automodpack
3. wait for mods to install then click quit game
4. relaunch minecraft
5. check mods folder

### Expected behavior

After it says "An update has been downloaded for your modpack!" and you restart your game all the mods should be added and you should be able to join the server without issues

### Actual behavior

After it says "An update has been downloaded for your modpack!" and i restart my game
i try joining the server to be met with "Recieved 254 registry entries that are unknown to this client. This is usually caused by a mismatched mod set between client and server."
And when looking at mods folder i find no mods except automodpack

### Relevant logs

Client: 
[latest.log](https://github.com/Skidamek/AutoModpack/files/11852541/latest.log)
Server: 
[latest.log](https://github.com/Skidamek/AutoModpack/files/11852559/latest.log)

### Minecraft version & Mod Loader

1.19.4

### Operating system

Windows 11

### AutoModpack version

3.3.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Try this:
stop the server entirely
delete manually modpack-content.json from /automodpack/host-modpack/ on server
and start the server again

**Comment by Hexiph** [comment]
same issue :/  i fully deleted it and restarted the server

**Comment by Skidamek** [comment]
ah alright, i think what i've typed worked, but modpack hash didn't change because of how generating logic works, could you now delete /automodpack/modpacks/ folder from client?

**Comment by Skidamek** [comment]
or just change anything on server's modpack and regenerate it by executing /automodpack generate

**Comment by Hexiph** [comment]
> ah alright, i think what i've typed worked, but modpack hash didn't change because of how generating logic works, could you now delete /automodpack/modpacks/ folder from client?

ive done this multiple times but will try to /automodpack generate

**Comment by Hexiph** [comment]
k thanks

**Comment by Skidamek** [comment]
There it is https://github.com/Skidamek/AutoModpack/suites/13827877726/artifacts/767566458

**Comment by Hexiph** [comment]
The new jars crash the server but are loaded fine on the client

**Comment by Hexiph** [comment]
heres the log if you need it
[latest.log](https://github.com/Skidamek/AutoModpack/files/11852924/latest.log)

**Comment by Skidamek** [comment]
Crash server? Could you send log?

**Comment by Shrimplonex** [comment]
> The new jars crash the server but are loaded fine on the client

Try running server without the jar with "sources" in its name. Server loads fine this way for me, fabric 1.20 - However, clients still have to manually update to the manual installation of 3.3.5 in order to join which.. isnt optimal.

**Comment by Shrimplonex** [comment]
> > The new jars crash the server but are loaded fine on the client
> 
> Try running server without the jar with "sources" in its name. Server loads fine this way for me, fabric 1.20 - However, clients still have to manually update to the manual installation of 3.3.5 in order to join which.. isnt optimal.

and actually now realizing too, it will download/update the mods once, if you were to change something again and restart it wont. So there's still some key issue here.

**Comment by Hexiph** [comment]
> > The new jars crash the server but are loaded fine on the client
> 
> Try running server without the jar with "sources" in its name. Server loads fine this way for me, fabric 1.20 - However, clients still have to manually update to the manual installation of 3.3.5 in order to join which.. isnt optimal.

weird i did that and it crashed

**Comment by Hexiph** [comment]
probably a mod incompatability

**Comment by Hexiph** [comment]
i think 1.20 works but 1.19.4 doesnt

**Comment by Hexiph** [comment]
> > > The new jars crash the server but are loaded fine on the client
> > 
> > 
> > Try running server without the jar with "sources" in its name. Server loads fine this way for me, fabric 1.20 - However, clients still have to manually update to the manual installation of 3.3.5 in order to join which.. isnt optimal.
> 
> and actually now realizing too, it will download/update the mods once, if you were to change something again and restart it wont. So there's still some key issue here.

what version of fabric were you using

**Comment by Skidamek** [comment]
released 3.3.5 should fix all of this

**Comment by Skidamek** [comment]
just restart server and clients and everything should work

**Comment by Skidamek** [comment]
Write message here if this doesn't work again, i will reopen the issue

**Comment by Auxioni** [comment]
It's still broken. It says that it downloads it, but nothing actually appears in the mods folder. And if you join the server after it has "downloaded" mods, it let's you right in as if they actually have been installed.

**Comment by Skidamek** [comment]
Could you send yours server's modpack-content.json?

**Comment by Skidamek** [comment]
Hopefully finally fixed in 3.3.6

**Comment by Skidamek** [comment]
Ok now. Re-download latest jar if you have downloaded previous 3.3.6 sorry lol

**Comment by Hexiph** [comment]
I dont know if this should be put as its own issue but the same bug is occuring for the config files (it says it downloads them but they never change in game)

**Comment by Skidamek** [comment]
If you have steps to reproduce that, please make a new issue

**Comment by Hexiph** [comment]
yeah sure
