### ISSUE TITLE
Once again, mods not actually installing.

### ISSUE THREAD

**Issue by Shrimplonex** [Skidamek/AutoModpack#133]
### Bug description

Modpack content.json is being updated, clients mod content list is being updated, but it's not actually downloading the mods. Worked litearlly just a little bit earlier today, i dont even think it was 3.3.4 that broke it. Did you change something in 3.3.4 and just uploaded a new version of 3.3.4 instead of 3.3.5? Or did it just magically break out of nowhere?

### Steps to reproduce

Same as before.

Open client
Modpack sucessfully downloaded
Look at the mods folder, notice there's no new mods in it

### Expected behavior

Expect the mods to actually download

### Minecraft version & Mod Loader

1.20

### Operating system

Windows 10

### AutoModpack version

3.3.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Shrimplonex** [comment]
Using the 3.3.5 patch on the server downloads the mods correctly. However 3.3.5 isnt released anywhere so automodpack does not automatically update to 3.3.5

**Comment by Shrimplonex** [comment]
Removing the client's modpack-content.json causes the popup of "installing these mods" and says its installing them, but once again it doesnt actually do it.

My personal suggestion since "optimizing" seems to continuously break it, is maybe just leave it alone for a bit when you get it working again :P

**Comment by Skidamek** [comment]
alright released 3.3.5
