### ISSUE TITLE
Deletes Config Files seconds after they get downloaded

### ISSUE THREAD

**Issue by Hexiph** [Skidamek/AutoModpack#135]
### Bug description

Whenever i join my server it says it downloads all the config files but when i relaunch the game all of them are set to default and it does this everytime i restart the server.

### Steps to reproduce

1. install automodpack-mc1.19.4-fabric-3.3.6
2. join server with edited config files
3. wait for the config files to download
4. relaunch minecraft
5. check configs

### Expected behavior

when i join the server it will install all the config files right to the client and they will be update when i join

### Actual behavior

when i join the server it says it installed all the config files but in reality when you relaunch the game they are still set to default

### Minecraft version & Mod Loader

1.19.4

### Operating system

Windows 11

### AutoModpack version

3.3.6

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Could you check if the issue persist on 3.3.7? If so, please send client and server log with server's modpack-content.json, i need more information.

**Comment by Hexiph** [comment]
Everything is fixed in 3.3.8

**Comment by Skidamek** [comment]
Great, thank you! :)
