### ISSUE TITLE
Mod Not Automatically Downloaded Afterwards(1.20.1 fabric)

### ISSUE THREAD

**Issue by maozi20017** [Skidamek/AutoModpack#142]
### Bug description

I'm not sure if this is the correct configuration.

### Steps to reproduce

1.I installed some mods and joined the server after opening it. 
2.The mods were automatically downloaded. 
3.Later, I installed a few more mods on the server, but these newly added mods are not automatically downloaded.

### Expected behavior

client side will download newly added mods

### Actual behavior

it didn't

### Minecraft version & Mod Loader

1.20.1 fabric

### Operating system

Windows11

### AutoModpack version

3.4.2

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Should be fixed in 3.4.3
