### ISSUE TITLE
[1.20.1 Forge] ATLauncher incompatibility - client auto update relaunch stuck infinitely

### ISSUE THREAD

**Issue by MrKashew** [Skidamek/AutoModpack#145]
### Bug description

![image](https://github.com/Skidamek/AutoModpack/assets/53996665/9a19820a-970d-434f-a470-4759fb1785df)
let me know if more log data is necessary

### Steps to reproduce

During client auto update phase of launch

### Minecraft version & Mod Loader

1.20.1, Forge 47.1.43

### Operating system

Windows 10

### AutoModpack version

3.4.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
What does hanging on config means?

**Comment by MrKashew** [comment]
sorry - meaning it gets stuck on this step

**Comment by MrKashew** [comment]
removed player companions and artifacts mods as they are the last 2 to be logged, issue still happening (infinite loading)

**Comment by MrKashew** [comment]
generated another modpack on my server and it gets stuck here now, not really finding any useful info to log
https://gyazo.com/07b0b8668891f777ef821e7243937c5d

**Comment by MrKashew** [comment]
I was able to bypass the launch stuck by deleting contents inside automodpack/modpacks/{{server-ip}}
however this triggers an update option upon trying to join the server
if click yes + relaunch, then it comes back to the same issue

**Comment by Skidamek** [comment]
did you try with newer build i send you already few times?

**Comment by MrKashew** [comment]
currently using automodpack-mc1.20.1-forge-3.4.3+build.82

**Comment by Skidamek** [comment]
Without automodpack it loads?

**Comment by MrKashew** [comment]
yes, it currently launches if I either delete contents inside `automodpack/modpacks/{{server-ip}}` (until relaunch) or delete automodpack mod, I'll see if I can get more info it is driving me a bit mad

**Comment by Skidamek** [comment]
https://github.com/Skidamek/AutoModpack/suites/14543851898/artifacts/823119410

**Comment by MrKashew** [comment]
narrowed the bug down
It happens when using the Forge mod with ATLauncher (any forge version 47.1.3 and above!)
I tried it with Vanilla Minecraft Launcher and it worked like a charm

A bit unfortunate however as ATLauncher is my favorite launcher
I wonder if it is JVM argument related to the launcher or the launcher / instancing itself

**Comment by MrKashew** [comment]
I've unblocked by moving to prism launcher - no longer have the issue, seems ATLauncher specific

**Comment by Skidamek** [comment]
It may fix this https://github.com/Skidamek/AutoModpack/suites/14637674445/artifacts/830252211

**Comment by Skidamek** [comment]
Should be fixed in 3.4.4 if not just use prism lol
