### ISSUE TITLE
[1.20.1 Forge] Removing mod files are not being removed from client

### ISSUE THREAD

**Issue by MrKashew** [Skidamek/AutoModpack#146]
### Bug description

I delete the mod from mods / moved it to a subdirectory trash folder called `crashing` that I use for debugging
![image](https://github.com/Skidamek/AutoModpack/assets/53996665/668dd468-a6b7-4861-bb75-31c9c55e6ce7)
however it is still in mods folder after autoupdating
![image](https://github.com/Skidamek/AutoModpack/assets/53996665/7396e406-6ae0-4c14-abfc-5ae478e969ab)

### Steps to reproduce

delete mod from modpack
run client autoupdate

### Minecraft version & Mod Loader

1.20.1, Forge 47.1.43

### Operating system

Windows 10

### AutoModpack version

3.4.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Please try this build https://github.com/Skidamek/AutoModpack/actions/runs/5653297693

**Comment by Skidamek** [comment]
What is the bug here? Please fill the bug form!

**Comment by MrKashew** [comment]
Issue is removing a mod from /mods on server will not remove it from /mods on client during autoupdate

**Comment by MrKashew** [comment]
#145 is soft blocking me from testing fix, will validate after

**Comment by MrKashew** [comment]
was able to unblock myself as issue actually is caused by ATLauncher, tested on vanilla - this issue is fixed for me
