### ISSUE TITLE
Mods-Cleint Folder

### ISSUE THREAD

**Issue by Ethmangameon** [Skidamek/AutoModpack#148]
### Motivation

I have a server that recives updates to mods often and my freinds are angry at me for constantly sending them more mods. I would like to use this mod but im having issues with setting it up with the mods i want like oculus the server freaks out with it installed and i do not wish to be using the current method of uploading the mods to goolge drive.

### Description

An issue im having on forge where i cant put oculus in the server or it crashes but i want it in the modpack and its not just oculus you cant put alot of cleint mods in the server without it crashing. I suggest a to add config option to make another folder the mods folder on the cleint, for ex mods-cleint(on server) = mods (folder on cleint). another way you could have it (idk if its possible most likely a forge issue) have a config option to tell the server not to load certain mods by renaming them like random.jar.disabled
and sending the cleint the random.jar or tell forge to just not load the mods

**Comment by Skidamek** [comment]
Hey! Is my readme that unreadable? you can put mods which you don't want to load on server to `/automodpack/host-modpack/mods/` as well as any other type of file

**Comment by Skidamek** [comment]
Cheers! https://github.com/Skidamek/AutoModpack#do-you-want-to-add-more-content-to-your-modpack
