### ISSUE TITLE
Feather Client

### ISSUE THREAD

**Issue by MrCubicYT** [Skidamek/AutoModpack#154]
### Bug description

Mods don't load with feather client.

### Steps to reproduce

1. Either download Automodpack from the feather mods browser or drag the Automodpack file into feather
2. Start Minecraft
3. Join a Minecraft server with Automodpack
4. Wait for Automodpack to download all the mods
5. Close Game
6. Start Game
7. It says modpack applied and sends you back to the Feather client launcher

### Expected behavior

Mods load on Feather after installing mods from server.

### Actual behavior

When you start the game after installing mods it just says "Modpack applied".

### Relevant logs

No Logs

### Minecraft & Mod Loader versions

Any version supported by Automodpack and Feather I presume

### Minecraft launcher

Feather Launcher

### Operating system

Windows 10

### AutoModpack version

3.4.4

### Other information

I think it could be fixed if Automodpack detects the launcher is feather and puts the mods in /.feather/user-mods/{version}-fabric

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by SettingDust** [comment]
May relate to https://github.com/Skidamek/AutoModpack/blob/main/src/main/java/pl/skidam/automodpack/Preload.java#L48
Shouldn't using hardcoded mods path. Using the const from loaders such as FMLPaths, FabricLoaderImpl.

https://github.com/SettingDust/ModSets/blob/67f2f2a61b6496c1c2395fe4d75b9819e1ad91c8/fabric/src/main/kotlin/settingdust/modsets/fabric/FabricSetupModCallback.kt#L71
https://github.com/SettingDust/ModSets/blob/main/forge-mod-locator/src/main/java/settingdust/modsets/forge/service/ModSetsModLocator.java#L84
https://github.com/QuiltMC/quilt-loader/blob/develop/src/main/java/org/quiltmc/loader/impl/QuiltLoaderImpl.java#L287

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
