### ISSUE TITLE
Majrusz's Accessories incompatibility? Can't join server

### ISSUE THREAD

**Issue by Brayman4k** [Skidamek/AutoModpack#156]
### Bug description

![Sem título](https://github.com/Skidamek/AutoModpack/assets/90104128/2547f64b-1641-4952-9ae5-1dd386c29d3e)

Happens when I try to join the world with the automodpack mod installed. If I download the mods using the automodpack, and unistall it, I can join the server.

### Steps to reproduce

1. Installed "automodpack" on an existing server/world
2. Create a new instance and download the mods through automodpack
3. Restart the game
4. Attempt to join the server/world

### Relevant logs

File was too big for pastebin:
https://drive.google.com/file/d/1whNd9sqXx1rAh8KnPL31i3lYjlv6ACns/view?usp=sharing

### Minecraft & Mod Loader versions

1.20.1 forge 47.1.43

### Minecraft launcher

Official Launcher and Curseforge Launcher

### Operating system

Windows 11

### AutoModpack version

3.4.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
huh strange, could you send whole zipped modpack?

**Comment by Brayman4k** [comment]
Yes, of course. Here it is: https://drive.google.com/file/d/117VR2xY4h0BVRqxNb01R-_dIj3GpQLMc/view?usp=drive_link
One more thing: I did some tests and apparently the error does not occour if its a fresh new world. If I try to connect to the existing world tho, I get the error

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
