### ISSUE TITLE
[Forge 1.20.1, v3.4.5] Timeout on joining server

### ISSUE THREAD

**Issue by MrKashew** [Skidamek/AutoModpack#162]
### Bug description

Prism Client Log:
https://mclo.gs/fnrWP8b

Server logs;
[latest.log](https://github.com/Skidamek/AutoModpack/files/12364056/latest.log)
[debug.log](https://github.com/Skidamek/AutoModpack/files/12364057/debug.log)

![image](https://github.com/Skidamek/AutoModpack/assets/53996665/952960f5-5000-4a93-a92c-86cf1e7fa0f1)

Also sent similar details on discord but reposting for a ticket as it seems reproducible

### Steps to reproduce

Start server with Automodpack 3.4.5
Attempt to join with client with 3.4.5
I didn't run into this issue with 3.4.4 (I had a separate issue of decoderExceptions on 3.4.4 upon joining that was not present once removing Automodpack mod - but I tried to update to 3.4.5 to see if the issue had been fixed on 3.4.5)

### Minecraft & Mod Loader versions

1.20.1, Forge 47.1.43

### Minecraft launcher

Prism

### Operating system

Windows 10

### AutoModpack version

3.4.5

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Could you try with latest build? https://github.com/Skidamek/AutoModpack/actions/runs/6126072400

**Comment by MrKashew** [comment]
Able to connect now! - but had to remove 2 clientside mods due to incompatibility crash (will create sep ticket for this, likely even a Fabrric Networking bug)
