### ISSUE TITLE
AutoModpack Stuck at launching games

### ISSUE THREAD

**Issue by JulesMellot** [Skidamek/AutoModpack#164]
### Bug description

Hi guys, 
For a few days now, I've been testing the mod. And I have to say that I love it, but I have a problem with it. I can't launch the game anymore. I started on the Mojang launcher, then on GDLauncher, and then on Prism.

So, I've been trying to figure out where the bug might be coming from, but I'm stuck at two points :/

1st point, when the launcher starts the game, the logs state: 
[21:13:37] [main/INFO]: Checking if AutoModpack is up-to-date...
[21:13:37] [main/INFO]: Didn't find any updates for AutoModpack! You are on the server version: 3.4.4
[21:13:37] [main/INFO]: Modpack hash is different than server modpack hash
[21:13:37] [main/WARN]: Modpack update found

The second point occurs when it gets stuck and displays:
[21:13:37] [main/INFO]: Finished fetching urls in 327ms
[21:13:37] [main/INFO]: In queue left 2 files to download (2kb)

Between the two points, it does check that all the mods are already installed and in the correct version. Since nothing has changed, it goes through all of them. like that : 

[21:13:37] [main/INFO]: Skipping already downloaded file: /mods/tech_enhanced-1.0.3.jar

### Steps to reproduce

1. Install the mod on Client side and Server side
2. Launch the game, go to server to download mod
3. Restart client
4. I can connect to server
5. The next day, game won't launch

### Relevant logs

all the log (from Prism): https://pastebin.com/MhHX5QUN

### Minecraft & Mod Loader versions

1.20.1

### Minecraft launcher

Vanilla, GDLauncher, Prism

### Operating system

Windows 11

### AutoModpack version

3.4.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by JulesMellot** [comment]
Hi ! I think the issue is with the hash thing. I ran multiple minecraft session with differents laucnher. First day : no problem. Second day all the launcher say : Modpack hash is different than server modpack hash. Then try to download everything then stuck.

**Comment by EscapeAltDelete** [comment]
Having the same issue.

**Comment by JulesMellot** [comment]
I found the issue. This is from the server side. Set "generateModpackOnStart" to false on the server.

**Comment by JulesMellot** [comment]
And delete automodpack directory in the minecraft folder. Then Restart and go to server

**Comment by Skidamek** [comment]
If you are on fabric, automodpack 3.4.3 shouldn't have this issue, i am working on it

**Comment by Skidamek** [comment]
fixed in 3.5.0
