### ISSUE TITLE
[Forge 1.20.1] Entity sound effects are INCORRECT / randomized

### ISSUE THREAD

**Issue by MrKashew** [Skidamek/AutoModpack#166]
### Bug description

Attached video of evidence
https://streamable.com/0ox9k2
Log (client): https://mclo.gs/lB2Yxzh
Logs (server):
[debug.log](https://github.com/Skidamek/AutoModpack/files/12443880/debug.log)
[latest.log](https://github.com/Skidamek/AutoModpack/files/12443882/latest.log)

Seems the **networking API** ([Forgified Fabric API](https://modrinth.com/mod/forgified-fabric-api/changelog)) is handling in game networking as well?
Perhaps a bug on this end, otherwise cannot see the scope of this mod affecting the gameplay like so as it should only affect mod synchronization
Removing Automodpack fixes for me so I know issue is with the mod sadly (using 3.4.4 currently as 3.4.5 doesn't work for me due to this issue #162)

### Steps to reproduce

Run server with the mods detailed in log (here is clientside .rar, server is same minus the "clientside" folder)
https://drive.google.com/file/d/1grCpgm2DYZVGIos3VNz3ssrjB_wHDMSI/view?usp=sharing
Join as client after synchronization

### Minecraft & Mod Loader versions

1.20.1, Forge 47.1.43

### Minecraft launcher

Prism

### Operating system

Windows 10

### AutoModpack version

3.4.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by MrKashew** [comment]
A few times this is happening for me with clientside mods (when only on client) and at other time with bothside mods e.g. EvilCraft

**Comment by Skidamek** [comment]
Could you try with latest build? https://github.com/Skidamek/AutoModpack/actions/runs/6126072400

**Comment by MrKashew** [comment]
Bug is still occuring (Forge 47.1.3 on 1.20.1)

Evidence:
https://streamable.com/drioqi
Modpack used for replication:
https://drive.google.com/file/d/1UE4yVYmhR90DZXByB73IytaGSms6wWdi/view?usp=sharing

**Comment by Skidamek** [comment]
Could you try instead of automodpack, install just [FFAPI](https://modrinth.com/mod/forgified-fabric-api) to your mods and check if this bug still occurs? If so, it will be good to report this issue to them

**Comment by MrKashew** [comment]
@Skidamek I finally got around to it (had to fix some mod incompatibilities with newer versions of AMP and FFAPI)
I can confirm, on latest AMP I am having the sound bug
On latest FFAPI I am _not_ having the sound bug

**Comment by MrKashew** [comment]
confirmed this is present on 3.5.2

**Comment by Skidamek** [comment]
Should be fixed in 4.0.0 beta 1
Let me know then i will reopen the issue
