### ISSUE TITLE
replay crash

### ISSUE THREAD

**Issue by Renderthegreat** [Skidamek/AutoModpack#172]
### Bug description

the game gets stuck on loading a replay

### Steps to reproduce

1. install replay mod
2. create a replay
3. join the replay mod

### Expected behavior

the replay loading in

### Actual behavior

it gets stuck

### Minecraft & Mod Loader versions

1.20

### Operating system

windows 10

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
