### ISSUE TITLE
Wiki page about how to use external proxies like hamachi

### ISSUE THREAD

**Issue by slodkipiesio** [Skidamek/AutoModpack#173]
### Bug description

Ok, so, Im playing with my friends using my laptop as a host and using hamachi to connect to the server, i can join it, but, when a friend is trying to connect they get an error:cant join the server, ask an admin to check logs, the logs show this and idk why isnt it working

### Steps to reproduce

1. download a quilt server
2. download hamachi
3. start the quilt server and install qfapi to it
4. install automod both for clients and for the server
5. join using hamachi

### Expected behavior

client can join

### Actual behavior

client can't join

### Relevant logs

[2023-09-24-5.log](https://github.com/Skidamek/AutoModpack/files/12708416/2023-09-24-5.log)

### Minecraft & Mod Loader versions

1.20 Quilt 0.20.2

### Minecraft launcher

Server + hamachi

### Operating system

windows 11

### AutoModpack version

quilt 3.5.2

### Other information

the issue only occurs for people joining through hamachi, i can join the server from my laptop

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
AutoModpack now doesnt require additional port
