### ISSUE TITLE
modpack-content.json is generated incorrectly

### ISSUE THREAD

**Issue by zecheki** [Skidamek/AutoModpack#175]
### Bug description

Some mod's modId in modpack-content.json is generated duplicatly.
It seems that modpack is updated successfully when client runs its function but the problem is happened after restart.
The files(whose modId is duplicated) are generated but are removed from client's mod folder when client is terminated for restart.

### Steps to reproduce

1. Start the server.
2. Generate modpack-content.json (auto)
3. Start the client.
4. Connect to the server and update.
5. Terminate the client for restart. ( After this point, files are deleted. )

### Expected behavior

The modId of modpack-content.json is generated so that it does not overlap with each other.
Or
The files are not deleted when the client restarts.

### Actual behavior

Some modId of modpack-content.json is generated so that it overlaps with each other.
And 
The files(whose modId is duplicated) are deleted when the client restarts.

### Minecraft & Mod Loader versions

1.20.1 forge 47.1.3

### Minecraft launcher

curseforge

### Operating system

Windows 11

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1! It does not save modid's anymore as it isnt needed
