### ISSUE TITLE
1.20.2 Compatibility

### ISSUE THREAD

**Issue by Jackuhlf** [Skidamek/AutoModpack#178]
### Motivation

To have this pack for 1.20.2

### Description

when will this mod be for 1.20.2?

**Comment by Skidamek** [comment]
It is not released yet because there are some issues I want to address before release, so don't close this issue. However if you just want to have working build for 1.20.2, you can find it there https://github.com/Skidamek/AutoModpack/actions/runs/6274315810

**Comment by Skidamek** [comment]
Arrived in 4.0.0 beta 1!
