### ISSUE TITLE
Download option

### ISSUE THREAD

**Issue by SaviorD22** [Skidamek/AutoModpack#179]
### Motivation

add an option that selects if to use URLs to download mods or directly download them from the server

### Description

When I donwload mods from my server it grabs URLs, but this sometimes causes issues, can there be a way to directly download the files from the server itself?

**Comment by Skidamek** [comment]
What problems it causes?

**Comment by Skidamek** [comment]
It is like that because it's only way I know I can *somehow* support other mod developers, by downloading as much resources as we can from theirs modrinth and curseforge pages. If it couses any problems, it would be better to address them instead of removing/disabling the whole feature.

**Comment by SaviorD22** [comment]
got it
