### ISSUE TITLE
Sometimes it has problem with unzipping

### ISSUE THREAD

**Issue by Pipelek** [Skidamek/AutoModpack#18]
**Describe the bug**
Sometimes it's not unzipping all files to folder mods

**Screenshots**
![unknown](https://user-images.githubusercontent.com/103743536/174539275-4650c409-67a9-47ff-867e-63b944ff7f30.png)

**Comment by Skidamek** [comment]
problem still exists

**Comment by Skidamek** [comment]
![image](https://user-images.githubusercontent.com/67871298/175982317-55d722c9-125d-4418-9c7d-ff990158ebfe.png)
another issue

**Comment by Skidamek** [comment]
maybe fixed, need more testing

**Comment by Skidamek** [comment]
Its still exists when game crash while modpack is unziping
