### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by SaviorD22** [Skidamek/AutoModpack#180]
### Motivation

I used 3.4.4 and it had a cool list of the mods being downloaded + a bar + cool music.  What happened to those? When I updated to the most recent version of the mod that's just gone... It was a cool feature, will it be back?

### Description

If possible it would be cool if it could have custom music :)

**Comment by Skidamek** [comment]
Huh, strange, that shouldn't be gone...

**Comment by SaviorD22** [comment]
will it be fixed next version?

**Comment by Skidamek** [comment]
Well if I will reproduce that then sure, what mc version and loader are you using?

**Comment by SaviorD22** [comment]
1.20.1 fabric loader 0.14.22

**Comment by SaviorD22** [comment]
using ver 3.5.2

**Comment by MrGreenTea** [comment]
I have this same issue as well, on my Windows Desktop and my Linux Laptop both.
- minecraft 1.20.1
- fabric 0.14.23 
- automodpack 3.5.2

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
