### ISSUE TITLE
[1.20.1 Forge] AMP is removing itself

### ISSUE THREAD

**Issue by MrKashew** [Skidamek/AutoModpack#181]
### Bug description

- This makes it remove itself from client upon sync
- Modpack content on server
[modpack-content.json](https://github.com/Skidamek/AutoModpack/files/12902377/modpack-content.json)
- Logs on server
[debug.log](https://github.com/Skidamek/AutoModpack/files/12902378/debug.log)
[latest.log](https://github.com/Skidamek/AutoModpack/files/12902380/latest.log)

### Steps to reproduce

- Run server with AMP
- Generate modpack
- Sync with client

### Minecraft & Mod Loader versions

1.20.1 Forge 47.1.3

### Operating system

Windows 10

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by MrKashew** [comment]
watching the /mods folder, it looks like it is removed on the relaunch specifically

**Comment by MrKashew** [comment]
confirmed also that this does not occur for me on 3.4.4

**Comment by MrKashew** [comment]
actually it seems it removes itself on client end as well, no longer sure how the issue happens

**Comment by MrKashew** [comment]
this issue is present in 3.5.0 as well

**Comment by Rockiecraft** [comment]
im having the same issue and it downloads only half the mods to the main mods folder in .minecraft but the modpack folder has all of them.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
