### ISSUE TITLE
"No Files to Download" As its downloading the files

### ISSUE THREAD

**Issue by BumbleTree** [Skidamek/AutoModpack#184]
### Bug description

Whenever i join the server and it has to install / update a new mod it always says that there are no files to download.
However after waiting it comes up with "An update has been downloaded" so it was downloading something.
Dont want people to cancel the download thinking its not doing andthing whislt actually it is.

### Steps to reproduce

Join server with a mod change needed

### Expected behavior

It to say its downloading

### Actual behavior

Says it has nothing to download

### Minecraft & Mod Loader versions

1.20.1 from Automodpack fabric installer

### Minecraft launcher

Standard

### Operating system

Windows 11

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by MrKashew** [comment]
having this issue as well

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
