### ISSUE TITLE
Blue Screen Error on Forge 47.2.1

### ISSUE THREAD

**Issue by Eslorex** [Skidamek/AutoModpack#185]
### Bug description

Game doesn't launch and displays a blue screen before closing

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Relevant logs

https://mclo.gs/1QwJNAa

### Minecraft & Mod Loader versions

Forge 47.2.1

### Minecraft launcher

Modrinth 

### Operating system

Windows 11

### AutoModpack version

automodpack-mc1.20.1-forge-3.5.2

### Other information

-

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Eslorex** [comment]
I can provide the modlist if needed.

**Comment by Skidamek** [comment]
Blue screen interesting, however working on an big update which reworks the forge build and will work much better than now, should be released soonish:tm: So modlist/log not needed there.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
