### ISSUE TITLE
Mod ignores download errors

### ISSUE THREAD

**Issue by FextraBlitz** [Skidamek/AutoModpack#187]
### Bug description

When a mod being downloaded encounters an error, all other mods stoop downloading, and automodpack adds the unfinished mods anyway to the mods folder and also occasionally reports that nothing went wrong.

I'm using Playit. I'm mentioning just in case it's a part of the issue

### Steps to reproduce

1. Have a bunch of mods
2. Generate as usual
3. Connect to server with client with automodpack (same version)
4. Wait for results

### Expected behavior

All mods actually finish downloading, or if ever one encounters an error, it should retry and  NOT stop everything and NOT add those unfinished downloads to the mods folder anyways

### Actual behavior

other mods dont finish downloading for some reason and bad mods get added anyways

### Relevant logs

Server logs:
[latest.log](https://github.com/Skidamek/AutoModpack/files/13218487/latest.log)

Client logs:
[latest.log](https://github.com/Skidamek/AutoModpack/files/13218477/latest.log)

### Minecraft & Mod Loader versions

Minecraft 1.20.1 Fabric 0.14.21

### Minecraft launcher

Prism Launcher

### Operating system

Windows 10

### AutoModpack version

 automodpack 3.5.2 (first observed with ver 3.4.5)

### Other information

It occurs most of the time, but very rarely, it does somehow finish downloading everything

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by FextraBlitz** [comment]
I suggest a few solutions:
1. Attempt to redownload files that failed to download
2. Don't replace any files in the main game folder if any file were to fail to download

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
