### ISSUE TITLE
Automodpack 3.5.2 just doesn't work as intended

### ISSUE THREAD

**Issue by RWRmrfrog** [Skidamek/AutoModpack#189]
### Bug description

Automodpack just isn't working as intended, thought I might post my issues here in the hopes that things are fixed or someone can tell me what I'm doing wrong. There are multiple issues here, spent 40 min trying to get one client set up with automodpack, other clients also have issues.

### Steps to reproduce

**Setup:**
-My server is a 1.20.1 quilt 0.20.2 server
-Friends are using the minecraft or modrinth launcher on windows
-Server is an ubuntu computer, running the same minecraft version
-Mods are hosted through the server on an open port
-Server mods are in the /mods/ folder, client mods are in /automodpack/host-modpack/mods/ folder

**Mods:**
https://drive.google.com/file/d/1Sr7y1tN2hTGmWaSVrOZV7-Ilbj29v7KE/view?usp=sharing

**automodpack-server.json:**
{
  "modpackName": "",
  "modpackHost": true,
  "generateModpackOnStart": true,
  "syncedFiles": [
    "/mods/",
    "/config/roughlyenoughitems",
    "/config/dim_height.json",
    "/config/lithium.json"
  ],
  "excludeSyncedFiles": [
    "/mods/iDontWantThisModInModpack.jar",
    "/config/andThisConfigToo.json",
    "/mods/andAllTheseMods-*.jar"
  ],
  "allowEditsInFiles": [],
  "optionalModpack": false,
  "autoExcludeServerSideMods": true,
  "hostThreads": 8,
  "hostIp": "[removed for obvious reasons]",
  "hostLocalIp": "[removed for obvious reasons]",
  "updateIpsOnEveryStart": false,
  "hostPort": 30037,
  "reverseProxy": false,
  "externalModpackHostLink": "",
  "selfUpdater": true,
  "acceptedLoaders": [
    "quilt"
  ]
}

### Expected behavior

Automodpack should be a simple way to automate the download process for people who don't like to manually install mods. But it should also allow players who want to manually install mods and customize their game the ability to do so. 

### Actual behavior

**What happens:**

-automodpack fails to load during first launch of quilt
-[#188](https://github.com/Skidamek/AutoModpack/issues/188#issue-1974850322)
-https://github.com/Skidamek/AutoModpack/issues/184#issue-1
-Connection sometimes times out
-You need qfapi to run it which wasn't stated on the mod page
-Some players crash when attempting to join the server after modifying some configs (tested without automodpack, modifying config files doesn't cause crash) (crash log attached)
-client must have automodpack to join the server

[crash-2023-11-03_02.12.56-client.txt](https://github.com/Skidamek/AutoModpack/files/13251989/crash-2023-11-03_02.12.56-client.txt)

### Minecraft & Mod Loader versions

1.20.1 quilt 0.20.2

### Minecraft launcher

Modrinth & Vanilla

### Operating system

Client - windows 10, Server - Ubuntu

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
However there's no quilt version yet, other issue will track that #168
