### ISSUE TITLE
Can't Join server with installed AutoModpack 3.5.3-SNAPSHOT

### ISSUE THREAD

**Issue by Y5R** [Skidamek/AutoModpack#190]
### Bug description

I try to connect to the server but it give me that error message:

![image](https://github.com/Skidamek/AutoModpack/assets/41449377/0e538bfb-87bd-4b17-9535-2a12a97eda6c)

Deleting AutoModpack from server side resolve connecting issue

### Steps to reproduce

1. Install AutoModpack 3.5.3-SNAPSHOT on Server
2. Update mods via AutoModpack
3. Try login to server

### Expected behavior

Joining the server

### Actual behavior

Error message appears: 

![image](https://github.com/Skidamek/AutoModpack/assets/41449377/b14c2e45-bb7c-4d87-ba16-0d5bea1813a4)

### Relevant logs

https://drive.google.com/drive/folders/1Pu94ovVAuYqlf1-qFAH9A5ReaZ4GKe4T?usp=sharing

### Minecraft & Mod Loader versions

1.20.1 Forge 47.1.3

### Minecraft launcher

Modrinth App

### Operating system

Win 11

### AutoModpack version

3.5.3 SHAPSHOT

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
