### ISSUE TITLE
1.19.2 forge

### ISSUE THREAD

**Issue by Rockiecraft** [Skidamek/AutoModpack#192]
### Motivation

I would like this mod for 1.19.2 forge if you're not already working on it

### Description

I would like this mod to be updated for forge 1.19.2 so i can use it for my server since i'm currently running forge 1.19.2

**Comment by Skidamek** [comment]
It is already being work on :)
You can expect it soon...

**Comment by Rockiecraft** [comment]
> It is already being work on :) You can expect it soon...

dude yes, thank you. Take your time in making this amazing creation, your work is much appreciated.

**Comment by Skidamek** [comment]
I will close this when it will be released

**Comment by Skidamek** [comment]
Arrived in 4.0.0 beta 1!
