### ISSUE TITLE
"/config/paxi/resourcepacks" matches "/resourcepacks/*" filter

### ISSUE THREAD

**Issue by No3371** [Skidamek/AutoModpack#194]
### Bug description

> /[04:46:24] [AutoModpackCreation-3/INFO]: File /config/paxi/resourcepacks/Translating/assets/automodpack/lang/zh_tw.json is editable!
>[04:46:24] [AutoModpackCreation-3/INFO] (AutoModpack) File /config/paxi/resourcepacks/Translating/assets/automodpack/lang/zh_tw.json is editable!
>/[04:46:24] [AutoModpackCreation-3/INFO]: File /config/paxi/resourcepacks/Translating/assets/emi/lang/zh_tw.json is editable!
>[04:46:24] [AutoModpackCreation-3/INFO] (AutoModpack) File /config/paxi/resourcepacks/Translating/assets/emi/lang/zh_tw.json is editable!

```
  "syncedFiles": [
    "/mods/",
    "/config/",
    "/resourcepacks/",
    "/scripts/"
  ],
  "excludeSyncedFiles": [
    "/mods/iDontWantThisModInModpack.jar",
    "/config/andThisConfigToo.json",
    "/mods/andAllTheseMods-*.jar",
    "/config/spark/*",
    "/config/urlmusicdiscs"
  ],
  "allowEditsInFiles": [
    "/resourcepacks/*",
    "/options.txt",
    "/config/emi.css",
    "/config/jade/*",
    "/config/chat_heads.json5",
    "/config/chatpatches.json5",
    "/config/diet-client.json5",
    "/config/iris.properties",
    "/config/lambdynlights.toml",
    "/config/pickupnotifications.toml",
    "/config/rpmtw_platform_mod.json5",
    "/config/shouldersurfing.toml",
    "/config/sodium-extra-options.json",
    "/config/sodium-options.json",
    "/config/sonance.config.json",
    "/config/stylisheffects-client.toml",
    "/config/treechop-client.toml",
    "/options.amecsapi.txt",
    "/config/sound_physics_remastered/*",
    "/config/power_config.json5",
    "/config/holdthatchunk.json"
  ],
```

### Steps to reproduce

Make the folders and put files

### Expected behavior

I don't see a reason regular path or string match would do this unless it's a contain().

### Minecraft & Mod Loader versions

1.20.1 Fabric 1.14.24

### Operating system

Windows 10

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
