### ISSUE TITLE
Update 1.20.3/4/5

### ISSUE THREAD

**Issue by KdGaming0** [Skidamek/AutoModpack#196]
### Motivation

To have this mod for 1.20.4 so I can use it on my server.

### Description

When will this mod be for 1.20.4?

**Comment by kangming06** [comment]
[Buggy version](https://github.com/kangming06/AutoModpack/actions/runs/7233201415)

**Comment by KdGaming0** [comment]
tanks

**Comment by Skidamek** [comment]
Arrived in 4.0.0 beta 1!
