### ISSUE TITLE
exclude mods from server but sync them to the client

### ISSUE THREAD

**Issue by Surio89** [Skidamek/AutoModpack#200]
### Motivation

In some cases i want the client to receive a mod thats not used by the server itself for example Oculus. Its part of the ATM9 Modpack. I would like to add a "client-mods" folder on the Server and map its content to the "mods" folder of the client. 

### Description

So i would like to add a folder mapping to the config file: {"client_mods":"mods", "client_config":"config"} for example. 

Other solution might be that i tag the unwanted mods for the server with the filename .disabledOnServer or something wich will be removed during transfer. The desired String could also be part of the config.

### Other information

 Or i missed a feature that makes this already possible?. Thank you.

**Comment by suerion** [comment]
You only need to add the client mods in the modpack folder, this will sync automaticly the client modpack ;)

**Comment by Skidamek** [comment]
https://github.com/Skidamek/AutoModpack#do-you-want-to-add-more-content-to-your-modpack
