### ISSUE TITLE
Don't work sync files via AutoModpack and custom folder for client modpack version.

### ISSUE THREAD

**Issue by KubisonFromKDE** [Skidamek/AutoModpack#202]
### Bug description

Don't work AutoModpack on my **server**. Everything is **described in the other sections**, so it would be pointless to write it several times.

**The modpack is intentionally split into a server version and a client version, due to technical difficulties and other reasons.**

### Steps to reproduce

In the server directory I have a client version of my own modpack which contains all the necessary files for the client (mods, configs, etc.).

### Expected behavior

I created a folder in the server directory called "**modpack**" and the folder contains **the client version of modpack**. As I expected, the plugin should **synchronize** the contents of the "**modpack**" folder with **the client's ".minecraft" folder**. So what the "**modpack**" folder contains (for example: mods, configs, etc), the mod should make the contents **sync** with the "**.minecraft**" folder.

Why is the "**modpack**" folder in the server directory?
Simple. I need to upload somebody's client version of the modpack.

### Actual behavior

![01](https://github.com/Skidamek/AutoModpack/assets/67206839/99788064-03b1-4a75-9b25-deddb3a14f58)

![02](https://github.com/Skidamek/AutoModpack/assets/67206839/45a4fc68-e6aa-4209-9ae2-170cccfca4b9)

![03](https://github.com/Skidamek/AutoModpack/assets/67206839/fe34acad-cc69-4c97-96a5-5005a928965e)

### Relevant logs

https://mclo.gs/c2kajT8

### Minecraft & Mod Loader versions

1.20.1 fabric 0.14.25

### Minecraft launcher

Vanilla Minecraft Launcher

### Operating system

Client: Windows 10, Server: Linux (Synology DSM, docker)

### AutoModpack version

3.5.2 (latest)

### Other information

You can write me here or on my discord 11th_doctor.

**Btw this mod has good features. Keep it up.**

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by TatleCat** [comment]
Yes, I need a separate mod package for the client

**Comment by Skidamek** [comment]
modpack directory should be in /automodpack/ directory

**Comment by Skidamek** [comment]
It shouldn't save null anyway

**Comment by Skidamek** [comment]
Hopefully fixed in 4.0.0 beta 1!
