### ISSUE TITLE
Try to Load Fabric API in 3.5.2Forge

### ISSUE THREAD

**Issue by mlus-asuka** [Skidamek/AutoModpack#203]
### Bug description

Called Fabric api in forge mod, and Jarjar in pack

### Steps to reproduce

can't run in forge

### Minecraft & Mod Loader versions

1.20.1 forge 47.2.1

### Minecraft launcher

HMCL launcher

### Operating system

Windows 11

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by ksk-waqs** [comment]
@Skidamek I confirm, it is ABSOLUTELY unworkable on forge and neoforge! 😞
![image](https://github.com/Skidamek/AutoModpack/assets/3883054/ae1bf42a-602d-41e3-af9e-f2ee10db3d69)

**Comment by Skidamek** [comment]
#183 duplicate
