### ISSUE TITLE
Chinese or other languages are not supported

### ISSUE THREAD

**Issue by TatleCat** [Skidamek/AutoModpack#204]
### Bug description

In the synchronized content, Chinese notes are not supported, and garbled characters will appear

### Steps to reproduce

Named mod after Chinese/other

### Expected behavior

Would like to be able to provide coding support, to find mods more intuitively...

### Minecraft & Mod Loader versions

1.20.1x0.15.3

### Operating system

Windows11

### AutoModpack version

3.5.2

### Other information

Sorry, I don't understand the technology...

### Check list

- [X] I have searched the existing issues and confirmed that this is not a duplicate.
- [x] I have verified that the issue persists in the latest version of the mod.

**Comment by Skidamek** [comment]
Probably will fix #199
