### ISSUE TITLE
Mod overrides config file at start and deletes client mods without permission

### ISSUE THREAD

**Issue by ComradeCaro** [Skidamek/AutoModpack#206]
### Bug description

I found this mod and I gotta say looked really cool and able to make it so my friends could join my server even if i updated it with no effort on their part however this mod suddently decided to ignore my very clear DO NOT include any files starting with "server-*" or server-*.jar" and that might have been easily fixable if there is a problem in that exclusion but the fact that the mod resets the config file makes excluding anything pointless!

### Steps to reproduce

1. Download the latest version of the mod on both client and server
2. Put some server only mods inside the server mods folder and make them start with "server-"
3. Open the automodpack config file in the server and exclude anything that starts with "server-"
4. Start the server
5. See it reset the config file and add everything to the contents folder
6. Make the client join and have it download all the serverside mods and in the process delete some mods that overlap WHILE RUNNING and replace them with the serverside ones even though they have the exact same content!
7. The log prints out 10000 lines of errors

### Expected behavior

Downloaded mods the client missed and excluded the mods it should

### Actual behavior

Resets config and breaks client

### Minecraft & Mod Loader versions

1.20.1

### Minecraft launcher

Prism Launcher

### Operating system

PopOS

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
