### ISSUE TITLE
Disable "selfUpdater" by default

### ISSUE THREAD

**Issue by DatCaptainHorse** [Skidamek/AutoModpack#207]
### Motivation

Issue is, the releases of this mod aren't stable. 3.5.0-3.5.2 versions don't work properly with Forge, 3.4.5 does not even load and 3.4.4 almost works except when joining server kicks you out due to packet issue caused by this mod.

With "selfUpdater" being enabled by default, AutoModpack can potentially update itself to a broken version.

### Description

In future versions of the mod, make "selfUpdater" disabled by default.

**Comment by Skidamek** [comment]
Done in 4.0.0 beta 1!
