### ISSUE TITLE
Something is not working

### ISSUE THREAD

**Issue by xJasper222** [Skidamek/AutoModpack#208]
### Bug description

![obraz_2024-02-09_172505151](https://github.com/Skidamek/AutoModpack/assets/99542821/d241a984-17d3-47fe-955a-ca7d594d6aab)

### Steps to reproduce

So i installed AutoModpack on my server and installed a mod gravestone and all i see is this idk maybe i did something wrong with installation

### Expected behavior

download mod

### Actual behavior

says what mod has to be downloaded

### Minecraft & Mod Loader versions

1.20.1 fabric

### Operating system

windows 10

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
