### ISSUE TITLE
Wall of text error when I attempt to join multiplayer server

### ISSUE THREAD

**Issue by Shibavek** [Skidamek/AutoModpack#209]
### Bug description

Whenever I try to join a friend's modded server I get a large wall of text of random assets and I have to close the game entirely to leave

![Screenshot 2024-02-13 173247](https://github.com/Skidamek/AutoModpack/assets/159964724/b94318e1-552a-45d8-b7f0-cffef9311ff5)

### Steps to reproduce

1. Open Minecraft
2. Go to Multiplayer
3. Attempt to join modded Multiplayer Server
4. Large error wall of text of random assets

### Expected behavior

For the mods to be downloaded

### Actual behavior

Large error wall of text of random assets and in the logs it spams:
OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error'

### Relevant logs

https://pastebin.com/F6B1p7y1

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.15.6

### Minecraft launcher

CurseForge

### Operating system

Windows 11 Home

### AutoModpack version

3.5.2

### Other information

OpenGL Error 1280

### Check list

- [x] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
