### ISSUE TITLE
CreativeCore incompatibility

### ISSUE THREAD

**Issue by Ghosttisty** [Skidamek/AutoModpack#210]
### Bug description

I need creativecore for many of my mods and I don't know what happens that when I start the game automatically closes without any error status. And I know that's the problem because I tried removing everything and putting only mod and it kept happening.

### Steps to reproduce

1. open your minecraft 2. doesn't work

### Minecraft & Mod Loader versions

1.20.1

### Operating system

11

### AutoModpack version

3.5.3 beta

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Ghosttisty** [comment]
If you download Sinytra Connector and its dependencies it works with version 3.5.3 snapshot of automodpack and creativecore it is crazy but it works

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!
