### ISSUE TITLE
1.19.2 Forge Version

### ISSUE THREAD

**Issue by metl-play** [Skidamek/AutoModpack#211]
### Motivation

Hello, I want a 1.19.2 Forge version to be added.

### Description

It looks like in the 1.19.2 branch, there is already the Forge Version but not compiled?
I want to use this mod in Combination with the Create Mod and others that on my end require 1.19.2 Forge for the greatest compatibility.

### Other information

If the code in the mentioned branch is working, I would try and compile it myself, I just need verification that it works.

**Comment by Skidamek** [comment]
Working on it

**Comment by Skidamek** [comment]
Btw create doesn't require forge, there's also fabric port

**Comment by metl-play** [comment]
Thank you very much, that's great to hear.
About fabric I started it on fabric but because of other mods I settled with forge.

**Comment by Skidamek** [comment]
Arrived in 4.0.0 beta1!
