### ISSUE TITLE
Connector - fabric on forge - mods won't load

### ISSUE THREAD

**Issue by Skidamek** [Skidamek/AutoModpack#214]

**Comment by TophC7** [comment]
Any updates on this issue? Currently the only thing keeping me form using automodpack :(

**Comment by Skidamek** [comment]
Ok, I've initially implemented workaround for these mods, so far from my limited testing it seems to work fine. Could you try it? [Here you download zipped dev build](https://github.com/Skidamek/AutoModpack/actions/runs/9813108055/artifacts/1672361748) its big because it contains all the versions.
