### ISSUE TITLE
Triggering windows defender

### ISSUE THREAD

**Issue by Rockiecraft** [Skidamek/AutoModpack#216]
### Bug description

windows virus & threat protection suddenly started flagging the mod as Trojan:Script/Wacatac.H!ml with the latest update for the mod

### Steps to reproduce

Simple trying to download it can flag it. or it can flag it when already on your pc

### Expected behavior

windows antivirus to flag it as Trojan:Script/Wacatac.H!ml

### Minecraft & Mod Loader versions

1.20.1, forge 47.2.20

### Minecraft launcher

Normal launcher

### Operating system

Windows 11

### AutoModpack version

4.0.0-beta1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Bruh... well I don't think I can do anything about it, or do I? you likely need to manually allow/approve it

**Comment by Rockiecraft** [comment]
I did manually allow it. but theres something apparently in it thats triggering windows antivirus. i just wanted to let you know about the bug just in case it is fixable. it was an easy work around but it was just kinda annoying. the mod works perfectly otherwise.

**Comment by Skidamek** [comment]
Can't reproduce on windows 10

**Comment by Skidamek** [comment]
Does it only happen for forge 1.20.1 build?

**Comment by Rockiecraft** [comment]
1.19.2 hasn't triggered it so far. so might be just 1.20.1.

**Comment by Skidamek** [comment]
I cant do anything about this, besides paying microsoft and then sigining every jar, no thanks

**Comment by Skidamek** [comment]
![image](https://github.com/Skidamek/AutoModpack/assets/67871298/7877ae50-681a-4200-8003-bfb377a49018)

**Comment by Rockiecraft** [comment]
didn't have anything in there saying that did you? lmao

**Comment by Skidamek** [comment]
I think no lol, but that's just an example how broken this defender really is
