### ISSUE TITLE
syncedFiles is rewriten on server startup

### ISSUE THREAD

**Issue by Y5R** [Skidamek/AutoModpack#217]
### Bug description

automodpack-server.json is been rewriten on server startup

automodpack-server.json before server start:
![image](https://github.com/Skidamek/AutoModpack/assets/41449377/8fca5711-11d3-4b66-a9e4-74ab9b27026c)

automodpack-server.json after server start:
![image](https://github.com/Skidamek/AutoModpack/assets/41449377/8dbb8ab6-0e7a-4fb1-83e6-b05e7431f194)

### Steps to reproduce

1. Stop server.
2. Make changes to syncedFiles section
3. Save file
4. Start server

### Expected behavior

Changes saved and applied

### Actual behavior

syncedFiles section reverts itself to initial values

### Minecraft & Mod Loader versions

1.20.1 Forge 47.1.3

### Minecraft launcher

Modrinth App

### Operating system

Windows 11

### AutoModpack version

automodpack-forge-4.0.0-beta1-1.20.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Works perfectly fine for me, can't reproduce. Could you upload relevant logs from server?

**Comment by Skidamek** [comment]
![image](https://github.com/Skidamek/AutoModpack/assets/67871298/c85d7618-ca02-4d17-8977-64848d23d5f3)
I see you have `,` on last entry, json doesn't like that, try without `,` on last one

**Comment by Y5R** [comment]
Did not helped.

Here logs: https://dropmefiles.com/Q66ko

**Comment by Y5R** [comment]
Found what was the problem!

You was right it because of missed `,` but after default lines.

All works as intended.

Thanks for help)
