### ISSUE TITLE
Cant load into Singleplayer world.

### ISSUE THREAD

**Issue by PhoxVRC** [Skidamek/AutoModpack#219]
### Bug description

When Automodpack is enabled I get the error "Failed to connect to server" after creating / loading a singleplayer world.

### Steps to reproduce

1. Create new world
2. Let it generate
3. Get screen "Failed to connect to server"

### Expected behavior

Load into the world just fine.

### Actual behavior

Loading into the world it has this error:
![image](https://github.com/Skidamek/AutoModpack/assets/42518848/2f9afb66-d673-4e39-b4e2-1822413bdf4f)

### Relevant logs

Error in the console, line 1266
https://mclo.gs/dKneqQe#L1266

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.15.7

### Minecraft launcher

Modrinth

### Operating system

Windows 11

### AutoModpack version

4.0.0

### Other information

It only happens trying to load into a single player world. Joining my multiplayer server works perfectly fine.

If I toggle automodpack off in Modrinth, singleplayer doesnt show that error.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Rockiecraft** [comment]
cant play on singleplayer on forge either.
![image](https://github.com/Skidamek/AutoModpack/assets/55363145/89f2fc4e-1e01-4e6b-89fe-838262daafa0)
in the log it says the same thing

**Comment by p2drin** [comment]
is it working now? not working for me :/

**Comment by Skidamek** [comment]
Haven't released yet because I think something yet may break but you can already download dev build from GitHub actions https://github.com/Skidamek/AutoModpack/actions/runs/8286188878/artifacts/1327224820

**Comment by Rockiecraft** [comment]
singleplayer worlds now work thanks. i installed it in just my folder but works fine with the public release thats on my server.

**Comment by Lucas-Valdemar** [comment]
> Haven't released yet because I think something yet may break but you can already download dev build from GitHub actions https://github.com/Skidamek/AutoModpack/actions/runs/8286188878/artifacts/1327224820

Excuse me, how exactly can I use the dev build? I downloaded the zip file from be2efc5 version in actions, extracted the files and tried to run gradlew.bat because from what I read in the gradle project, I wouldn't need to install the gradle app on my machine, since the wrapper is already in the files, however after almost 30m of compilation (or something like that) the command window closes and no .jar file appears in the folder.

**Comment by Skidamek** [comment]
There are already compiled jar files inside that zip, if you would want to build by your own then you would need to clone whole git repo

**Comment by MichelJonkman** [comment]
The text version of the exception on Forge:
```
Failed to connect to server

Internal Exception: net.minecraft.ResourceLocationException: Non [a-z0-9_-] character in namespace of location:
{\"loaders\":[\"forge\"],\"amVersion\":\"4.0.0-beta1\",\"moVersion\":\"1.20 1\"
```
