### ISSUE TITLE
AmbientSounds 5 doesn't sync correctly

### ISSUE THREAD

**Issue by rafaelkai** [Skidamek/AutoModpack#220]
### Bug description

The mod [AmbientSounds ](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)5 isn't correctly synced, preventing from entering the server. Maybe because of its file size? It's one of the biggest mods I've downloaded.

### Steps to reproduce

1. Include AmbientSounds 5 in an AutoModpack modpack
2. Sync your mods on the client
3. AmbientSounds 5 isn't correctly downloaded on the client

### Minecraft & Mod Loader versions

1.20.1 forge 47.2.0

### Operating system

Windows 10

### AutoModpack version

4.0.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Could you send your automodpack config (`/automodpack/automodpack-server.json`) and automodpack-content.json (`/automodpack/host-modpack/main/automodpack-content.json`) files from server?

**Comment by rafaelkai** [comment]
Sure:
[automodpack-server.json](https://github.com/Skidamek/AutoModpack/files/14623205/automodpack-server.json)

[automodpack-content.json](https://github.com/Skidamek/AutoModpack/files/14623206/automodpack-content.json)

**Comment by Skidamek** [comment]
All seems good, could you send client log when you are downloading this modpack?

**Comment by rafaelkai** [comment]
The first time the client tries to download the modpack it downloads everything correctly minus a few mods, including AmbientSounds:
https://mclo.gs/C8AGjHR

Next time the game is launched, while the game is loading AutoModpack manages to download every missing mod correctly but always failing with AmbientSounds, not allowing the game to load:
https://mclo.gs/Hxq9Tc0

**Comment by Skidamek** [comment]
Odd... A bit looks like too slow bandwidth... Could i join your server and check if i get the same issue? If that's not a problem for you of course, if not then send me please ip on discord: [skidam](https://discordapp.com/users/464522287618457631)
