### ISSUE TITLE
Forge 1.18.2 doesn't load 

### ISSUE THREAD

**Issue by Skidamek** [Skidamek/AutoModpack#221]

**Comment by bruhdead** [comment]
When will it be fixed?

**Comment by bruhdead** [comment]
![Error](https://github.com/Skidamek/AutoModpack/assets/149468503/66d59ba4-1810-495d-9788-3c6a1ca103b6)

**Comment by Skidamek** [comment]
It's fixed in dev, you can download that there https://github.com/Skidamek/AutoModpack/actions/runs/8317674272/artifacts/1333325852
