### ISSUE TITLE
Client getting disconnected when trying to join server 

### ISSUE THREAD

**Issue by cyberpenguin404** [Skidamek/AutoModpack#222]
### Bug description

![image](https://github.com/Skidamek/AutoModpack/assets/109865336/ac6824cb-f88f-4b48-9fda-9c646d4838bc)
![image](https://github.com/Skidamek/AutoModpack/assets/109865336/b85b81ff-261d-4c87-91c8-d5a59e00e49b)

When trying to join the server the client can't load in and gets disconnected

### Steps to reproduce

1. Install automodpack on both client and server on fabric 1.20.4
2. Try to join the server on the client
3. Client can't join

### Expected behavior

Client gets to see the modpack install screen and is able to join the server

### Actual behavior

The client disconnects after waiting a bit of time

### Relevant logs

https://pastebin.com/KtyZb62x

### Minecraft & Mod Loader versions

1.20.4 fabric 0.15.7

### Minecraft launcher

Modrinth

### Operating system

Windows 11

### AutoModpack version

4.0.0-beta-1

### Other information

I found a previous issue that sounds simular: https://github.com/Skidamek/AutoModpack/issues/130

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by murayuki** [comment]
I have found a problem similar to the current one
I turned off `generateModpackOnStart` on the server.

After restarting the server it doesn't seem to get the `automodpack-content.json` content correctly (I'm not sure about this).

The client joins the server without a download prompt, but when the administrator or console enters the `automodpack generate` command to regenerate the `automodpack-content.json` the client tries to join the server again and gets a prompt.
