### ISSUE TITLE
Mod Non working

### ISSUE THREAD

**Issue by bobbix06** [Skidamek/AutoModpack#225]
### Bug description

When i start miencraft and i join a aternos server with soem mdos that i dotn have and it dosent prompt anyting to downlaod them insthead it promps me some mdos that i dotn have by defualt

### Steps to reproduce

Joining a aternos sevrer without soem mods it has

### Expected behavior

prompts me to downlaod the mods

### Actual behavior

it dosent prompt me to download it instehad it shows a list of mods i need

### Minecraft & Mod Loader versions

1.20.1 Forge 47.2.20

### Minecraft launcher

curse forge launcher

### Operating system

Windows 11 Home 23H2

### AutoModpack version

4.0.0 Beta1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Please provide relevant logs from server and client. https://mclo.gs/

**Comment by Skidamek** [comment]
How do you load automodpack on aternos? I cant find it in theirs mods section...

I see it's denied cause in versions previous to 4.0.0 it needed to open new port but since it's not required anymore, it could be somehow re-suggested? i guess.

**Comment by bobbix06** [comment]
i only ahd it on the computer

**Comment by Skidamek** [comment]
You have to install it on server as well

**Comment by bobbix06** [comment]
i didnt have aucces to that server

**Comment by Skidamek** [comment]
than that's a problem, you could try reaching out to the aternos support and tell them that this mod doesn't require opening new port anymore and send them link to this github issue

**Comment by bobbix06** [comment]
they are gonna read this, btw i sne thte link
