### ISSUE TITLE
Wall of Text when trying to Join Server

### ISSUE THREAD

**Issue by GamerTable** [Skidamek/AutoModpack#228]
### Bug description

It was working fine before but today I tried to join after the server had some mods updated and the wall of text won't let me through...
I've tried deleting Automodpack and its configs. 
When I relaunch after downloading the modpack it does download it to the respective folders but when I relaunch the game it doesn't actually load the mods

### Steps to reproduce

1. Launch Game 
2. Download server Modpack
3. Relaunch game (No mods are loaded for some reason)
4. Scary Text 

### Expected behavior

It should let me join like normal

### Relevant logs

https://pastebin.com/tAF3kytp

### Minecraft & Mod Loader versions

1.20.1 

### Minecraft launcher

Modrinth

### Operating system

Windows 10 

### AutoModpack version

4.0.0 Beta 1

### Other information

I looked through the other issues and there was another guy experiencing the same Issue but it was marked as closed and fixed on the version I'm trying to use right now. 

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by GamerTable** [comment]
I searched through the Automodpack Modpack folder and the Content.json file is on defaults. 
![image](https://github.com/Skidamek/AutoModpack/assets/114619268/0ceb6f03-603f-41bd-87ea-ad49d0343a11)

**Comment by GamerTable** [comment]
> I searched through the Automodpack Modpack folder and the Content.json file is on defaults. ![image](https://private-user-images.githubusercontent.com/114619268/321030238-0ceb6f03-603f-41bd-87ea-ad49d0343a11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDczMjUsIm5iZiI6MTcxMjcwNzAyNSwicGF0aCI6Ii8xMTQ2MTkyNjgvMzIxMDMwMjM4LTBjZWI2ZjAzLTYwM2YtNDFiZC04N2VhLWFkNDlkMDM0M2ExMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMzU3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzE5MTBkNjdkYTJlYzAxNWI2ZTQwMGM3N2YzZWIzNjk4ZGQxOWQ3YzQ5Y2VlOGZmMjA5ZTg2NWY1ZTZlZmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8OQQe7KFajuUYjMP1Zocb6Dpe1V3AFrmbvBMVgRR15A)

Okay, I fixed the issue by copying the Content.json from another instance I had. Hope that helps lol.

**Comment by GamerTable** [comment]
Sorry for the continued comments, but everytime I join the Content.Json resets causing the issue again...

**Comment by Skidamek** [comment]
How your configs looks like?

**Comment by GamerTable** [comment]
Client.json https://pastebin.com/18TuMrMN
The Server's server.json https://pastebin.com/mWu56QcV

**Comment by Skidamek** [comment]
Try making updateIpsOnEveryStart false and hostPort -1

**Comment by Skidamek** [comment]
And make sure to every folder end with `/*` instead of just `/`

**Comment by GamerTable** [comment]
Nevermind, it also broke on the other players... It's so over

**Comment by Skidamek** [comment]
I don't understand this issue, could you send server log?

**Comment by GamerTable** [comment]
It's okay it started working when I reinstalled the mod on the server so... Sorry to bother lol
