### ISSUE TITLE
Exception when trying to load singleplayer world

### ISSUE THREAD

**Issue by MichelJonkman** [Skidamek/AutoModpack#229]
### Bug description

When I try to open a singleplayer world I get this exception:
```
Failed to connect to server

Internal Exception: net.minecraft.ResourceLocationException: Non [a-z0-9_-] character in namespace of location:
{\"loaders\":[\"forge\"],\"amVersion\":\"4.0.0-beta1\",\"moVersion\":\"1.20 1\"
```

The instance only has AutoModpack installed and no other mods.

### Steps to reproduce

Create or join a singleplayer world

### Minecraft & Mod Loader versions

1.20.1 NeoForge 47.1.104

### Minecraft launcher

Prism Launcher

### Operating system

Windows 10

### AutoModpack version

4.0.0-beta1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Duplicate #219
