### ISSUE TITLE
Forge 1.20.1 just displays normal mismatched mod list

### ISSUE THREAD

**Issue by MichelJonkman** [Skidamek/AutoModpack#230]
### Bug description

I have a simple server with a single mod (Domum Ornamentum) and a client with just AutoModpack installed both using the same NeoForge version.

### Steps to reproduce

Join the server using the client with the above explained environment

### Expected behavior

Getting the option to download the modpack

### Actual behavior

The mod mismatch list appears

### Relevant logs

https://mclo.gs/GgWnpb0

### Minecraft & Mod Loader versions

1.20.1 NeoForge 47.1.104

### Minecraft launcher

Prism Launcher

### Operating system

Windows 10

### AutoModpack version

4.0.0-beta1 (This also happens with [this Github action version](https://github.com/Skidamek/AutoModpack/actions/runs/8317674272))

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Huh strange does it happens only with Domum Ornamentum? Have you tried with other mod which is also required on client?

**Comment by MichelJonkman** [comment]
Tried Tax Free Levels (not required on client but still wanted) and Sophisticated Backpacks/Storage/Core (required client side).

With Tax Free Levels it didn't prompt to download and just continued on into the server.

When I added Sophisticated Backpacks/Storage/Core I did start getting a prompt to download the updated modpack and now it seems to be working. Didn't expect this behaviour so I never checked!

**Comment by Skidamek** [comment]
That's very strange... If you could upload also the client logs then

**Comment by MichelJonkman** [comment]
[Here you go](https://mclo.gs/yfVWfM4)

**Comment by Skidamek** [comment]
Thanks, no idea, something bad happens

**Comment by MichelJonkman** [comment]
Thanks for the quick response, it's not the worst since it fixes itself with more mods. Now that I think about it it might have something to do with the amount of mods? The times it didn't work I was only using a single mod

**Comment by Skidamek** [comment]
Will close when released fix
