### ISSUE TITLE
Add extra mods on client

### ISSUE THREAD

**Issue by MichelJonkman** [Skidamek/AutoModpack#231]
### Motivation

I want to be able to use some extra mods that aren't in the server modpack.

### Description

A way of adding extra mods on my client, if this feature already exists then this is a request to add that info to the README.md

**Comment by Skidamek** [comment]
Do you mean, that client independently uses additional mods?

**Comment by MichelJonkman** [comment]
Yeah, to me they can just be globally activated and not bound to a specific server

**Comment by Skidamek** [comment]
So, it's already a feature, this mod shouldn't delete other non modpack mods.
I have to rewrite this readme you right, it's a bit mess and doesn't contain enough information

**Comment by MichelJonkman** [comment]
I might've done something wrong or it's bugged then, I added Embeddium on my client while it wasn't on the server and it deleted the mod. I'll have to check that tomorrow

**Comment by MichelJonkman** [comment]
Just tried and it works now, don't know what I did wrong the first time. I might've removed it from the server and added it to my client at the same time

**Comment by Rockiecraft** [comment]
pretty sure automodpack doesn't touch mods that are in the same folder as it. so just put the mod in the same folder as the automodpack jar

**Comment by Skidamek** [comment]
Should be more understandable with new [wiki](https://github.com/Skidamek/AutoModpack/wiki) page
