### ISSUE TITLE
Files marked as editable still get redownloaded

### ISSUE THREAD

**Issue by MichelJonkman** [Skidamek/AutoModpack#233]
### Bug description

Files that should be editable by the client get redownloaded anyways

### Steps to reproduce

1. Sync a config file
2. Download modpack on client (and restart)
3. Change it on the client
4. Enter the server
It will redownload the changed file

### Minecraft & Mod Loader versions

1.20.1 NeoForge 47.2.23

### Minecraft launcher

Prism Launcher

### Operating system

Windows 10

### AutoModpack version

4.0.0-beta1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by suerion** [comment]
Had found a workaround for this. Because this issue is also on Fabric,

it download not the file again -> the issue happens on synchronizise from the Automodpack folder to the default config folder 

here a sample for automodpack ->

```  "allowEditsInFiles": [
    "/options.txt",
    "/servers.dat",
    "/config/voicechat/voicechat-client.properties",
    "/config/voicechat/*",
    "/automodpack/modpacks/MYMODPACK/config/voicechat/voicechat-client.properties"
  ],```
