### ISSUE TITLE
Specifically tell where will the files exist on the client

### ISSUE THREAD

**Issue by MindSetFPS** [Skidamek/AutoModpack#239]
### Motivation

I am currently having a problem: Embeddium and Oculus are two mods that I want clients to have, but when added to the server, they make it crash because it doesnt have access to certain screen properties.

### Description

The only way to ship them to the client without crashing is placing them inside a directory, because the modloader ignores .jar files inside directories in the /mods directory. For convenience, i called this folder "client", so my /mods folder looks like this:

`/mods/awesome-mod.jar`
`/mods/client/Embeddium.jar`
`/mods/client/mod-that-crashes-server-but-runs-in-cliet.js`

But now, the feature that kept this mods from crashing the server is also keeping the clients from running them, so now I would have to tell clients that they need to move the .jar files inside /mods/client to the parent directory. Not a big deal, but still not a perfect experiece.

How to fix that?

I propose to use the syncedFiles array from automodpack-server.json and add the source:target syntax to this string.

`"syncedFiles": [
    "/mods/client/*.jar:/mods/*"
]`

Meaning: take every file that ends with .jar in /mods/client in the server, and put them inside de mods directory in en client.

### Other information

I don't know much java, so I can't predict the viability of this feature, so I would like to know what you think about it. Have a nice day.

**Comment by Skidamek** [comment]
Leave these mods inside ```~/automodpack/host-modpack/main/mods/```

**Comment by Skidamek** [comment]
The problem is that my explanation in description isn't very clean, it should be changed but I am not sure how to rewrite it to be more understandable

**Comment by Skidamek** [comment]
Should be more understandable with new [wiki](https://github.com/Skidamek/AutoModpack/wiki) page
