### ISSUE TITLE
Support for adding Client-side only mods to the Modpack that the Server does not load

### ISSUE THREAD

**Issue by MiniCoperations** [Skidamek/AutoModpack#243]
### Motivation

To my knowledge there is no good way of adding clientside only mods to the modpack that the server itself does not try to load, this in particular has caused me a headache with distant horizons mod as it loads on a server but absolutely refuses to let the server run normally until it has been removed. Meaning that I have to get my clients to manually install/update it instead of installing it with AutoModpack.
Ideally, I would like to be able to add it to the pack so it is pushed to the clients but in a way that can skip the server loading it as a mod.

### Description

A seperate folder, maybe called 'Client Mods' or something that all client-side only mods can be added to which the server pushes to clients and puts them in the usual location for mods but that do not get loaded in any capacity on the server itself.

**Comment by Skidamek** [comment]
Read wiki https://github.com/Skidamek/AutoModpack/wiki/Modpack-Creation#two-ways-of-adding-content-to-the-modapck

**Comment by Skidamek** [comment]
I don't want to be mean but you haven't read that? Or is it that confusing? How to rewrite that page to be more clear then?

**Comment by Skidamek** [comment]
Sure no problem, let me know if that works for you
