### ISSUE TITLE
"editable" files are no longer applied on first modpack install

### ISSUE THREAD

**Issue by Ballisticannon** [Skidamek/AutoModpack#249]
### Motivation

I run a small server, which previously used AutoModPack-4.0.0-beta-1 to distribute its modpack to players. During development, I noticed that some of the mods we use have strange or overlapping keybinds, so I went into the server modpack and set up a custom options.txt file, shifting around the keys to be a bit more user-friendly. I then set this options file as "editable" in the AutoModPack server config file, and since we were on beta-1, that meant everyone who connected to the server would download and apply the options file when they first install the pack. After installation, the server wouldn't check the options file for differences, so people could tweak their own settings however they liked, and they'd be free to bring them onto the server without issue.

Recently, though, I noticed the updates that AutoModPack's been getting, so I updated the server to use 4.0.0-beta-10. Most of the changes have been excellent for us, but after some testing, I noticed that new players were no longer getting their options file updated when they first install the pack. As it turns out, the custom options file is still being _downloaded_, but it never actually gets applied, so the game just uses the same options.txt file it already had, and fills it up with all the weird keybinds.

After that, I did a little digging in the patch notes. If I understand correctly, it seems that the "feature" we were using to provide our players with a custom set of keybinds was actually a bug. According to the Modrinth changelog, it seems like it was patched out all the way back in beta-2, which mentions fixing a "bug where editable files would get downloaded anyway".

If this wasn't the intended behavior, I do understand why it would be patched out, but as our usage of the 4.0.0-beta-1 build has shown, there _is_ a clear use case. As it is now, our only choices are to leave the options file as fully _editable_, or to change it to be fully _non-editable_. If it remains editable, our new players can't benefit from the new keybinds unless they go and _manually_ replace their options.txt file with the one they downloaded - which is exactly the kind of fiddly thing that AutoModPack was meant to simplify. If we make it non-editable, then _nobody_ can customize their keybinds, their visual settings, their resource packs, and more, because the server will constantly try to reset their options files to match its own. However, if we were able to give certain files the old "editable" behavior from beta-1, then server owners using AutoModPack would be able to:

- Provide default keybinds, without forcing them to be used
- Set up suggested video settings, to help players avoid known performance issues and/or graphical errors (i.e. Create behaving strangely when graphical quality is set to "Fabulous")
- Provide clients with resource packs and shader packs which will be enabled by default after installation, without making them mandatory in order to play on the server
- Arrange for custom defaults in config files that should remain player-editable, which can be _huge_ for performance-intensive client-side mods such as Distant Horizons
- Set up a client's multiplayer server list to include new entries, while still allowing them to add their own servers afterwards

Beyond that, I'm sure there are all sorts of other applications, as well - these are just what I can come up with from my experience with tweaking options.txt, servers.dat, and the config folder.

### Description

As a server owner, I'd like to be able to set a list of files which are treated as non-editable for clients who don't yet have a file of the same name in the same directory, but are treated as editable for clients who already have such a file. The intent is that clients who connect to a server _without_ these files installed in their copy of the server's modpack would be made to download these files and have them applied as if mandatory, whereas clients who already have _some_ version of these files - no matter their contents - would be allowed to connect without the server enforcing any changes.

Ideally, this list would be set up through a new field in the automodpack-server.json config file, named something like "allowEditsAfterInstall". It would be nice if it used a similar syntax to the "allowEditsInFiles" field, allowing for wildcards and exclusions. If the files referenced in this new list overlap with the files referenced in "allowEditsInFiles", presumably the "allowEditsInFiles" category would override the other, but so long as one of the two lists has clear priority for all shared files, it should be fine.

**Comment by Skidamek** [comment]
You are right, it should work as it did previously. I likely won't add any new field for that case. It makes a lot more sense for editable files being always applied on first download. Not exactly sure what I was thinking while making the beta 2...

**Comment by Ballisticannon** [comment]
Ahh, I see. I appreciate the openness, and thank you for the prompt reply. For the sake of player convenience, I'll probably be reverting the server back to beta-1 until this feature returns in a future update, but I look forward to regaining all of AutoModPack's other improvements once that update does come out. Cheers, man.

**Comment by Ballisticannon** [comment]
If I could ask, is there any approximate date for when an update that fixes this issue might drop? I don't mean to rush, or anything - it just happens that I've recently brought down the server I mentioned earlier for debugging and maintenance, and I figured I might as well ask, just in case the timing works out.

**Comment by Skidamek** [comment]
Should be fixed now, needs testing

**Comment by Skidamek** [comment]
Should be fixed in beta 11
