### ISSUE TITLE
Automatic installation with coding errors and failure to install in place

### ISSUE THREAD

**Issue by AlexErrorX** [Skidamek/AutoModpack#251]
### Bug description

When I log in with the fabirc client, I can download normally, the name of the mod should be Chinese + English, but the result shows garbled characters (I don't know if this is related to this bug), and then after downloading, only part of the mod download is completed, and part of it is red, how to solve it?
![微信图片_20240721223121](https://github.com/user-attachments/assets/68194a89-d92d-443a-9fb8-873059925aa4)

### Steps to reproduce

1. Add the automodpack.jar to the server and open it normally
2. Open the automodpack client that has been added to enter the game
3. After connecting to the server, it shows normal download
4. can download mods but they are garbled
5. After downloading, it prompts to restart the game but no new mod is downloaded, as it is shown in red
6. Couldn't connet the server .

### Expected behavior

There is no gibberish and all mods can be installed, so you don't need to re-download it after restarting the game

### Actual behavior

The download is halfway through, restarts, then downloads and restarts again, and so on

### Minecraft & Mod Loader versions

1.20.1 fabirc0.16.0

### Minecraft launcher

pcl2

### Operating system

windows 11

### AutoModpack version

4.0.0 beta11 1.20.1 fabric

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Does it also occur on fabric loader 0.15.x?

**Comment by Skidamek** [comment]
And if it does, please try different well know worldwide launcher like prism, modrinth etc. please

**Comment by Skidamek** [comment]
And to the grabbled text, are you sure Minecraft font supports these characters? Could you try just write them on a minecraft chat?

**Comment by AlexErrorX** [comment]
> 它是否也发生在 fabric loader 0.15.x 上？

Yes, and it is not possible to actually install it

**Comment by AlexErrorX** [comment]
Yes, and it is not possible to actually install  mod

**Comment by AlexErrorX** [comment]
> 对于拼凑的文本，您确定 Minecraft 字体支持这些字符吗？你能试着把它们写在我的世界聊天中吗？
Yes, Chinese can be typed in the dialog of minecraft

**Comment by Skidamek** [comment]
> Yes, and it is not possible to actually install mod

Please try different launcher

**Comment by Skidamek** [comment]
stale
