### ISSUE TITLE
optional server and client side locations

### ISSUE THREAD

**Issue by 0belous** [Skidamek/AutoModpack#254]
### Motivation

Some client only mods like optifine crash the server on start, 
A way to control where synced file get put on the client would fix this by preventing the mod being loaded on the server but loading it on the client,
This could not only fix crashes it would also improve server performance by allowing less client only mods to be loaded.

### Description

For example:
/clientonlymods is not loaded by forge on the server but will be moved to a location on the client that is loaded
```
"syncedFiles": [
"/clientonlymods/*.jar" > "/mods"
|                         |
| - Server side folder    | - Where the files get put on the client
```

As stated in the title the syntax would be optional 
```
"syncedFiles": [
"/clientonlymods/*.jar" 
# behind the scenes gets sent to > "/clientonlymods"
```

This could also be used to sync the world to clients which is useful for servers that reset and players may want to have a world download
```
"syncedFiles": [
"/world" > "/saves/ServerName-2024-07-24"
```

This feature would require sanitization so malicious server owners cannot place files in arbitrary locations
```
"syncedFiles": [
"/malicioussoftware/*.exe" > "/../../../../../../../../../Windows/System32/"
```

**Comment by Skidamek** [comment]
[Read wiki](https://github.com/Skidamek/AutoModpack/wiki/Modpack-Creation) and just use `~/automodpack/host-modpack/main/`

**Comment by Skidamek** [comment]
And arbitrary locations are already handled [there](https://github.com/Skidamek/AutoModpack/blob/f4a81789486ebd697191688369351ed33886d938/loader/core/src/main/java/pl/skidam/automodpack_loader_core/client/ModpackUtils.java#L452-L475) client side.
