### ISSUE TITLE
Client startup crash when using certain combinations of local and modpack mods

### ISSUE THREAD

**Issue by n-zer** [Skidamek/AutoModpack#255]
### Bug description

Certain combinations of mods in the server modpack and the client's local mods folder may cause the client to crash on startup.

One such combination is PassthroughSigns (and dependencies) in the server's modpack, and Charmonium (and dependencies) in the client's local mods folder.

There is no crash when both mods are in the server's modpack or when both mods are in the client's mods folder. I suspect the crash has to do with the mods sharing a dependency (Fabric API) and the way AutoModpack handles duplicate mods in the modpack and the local mods folder.

### Steps to reproduce

1. Create a fresh server instance.
2. Add AutoModpack, PassthroughSigns, Forge Config API Port, and Fabric API to the server's modpack folder
3. Start the server
4. Create a fresh client instance with Fabric 0.16.0
5. Add AutoModpack, Charmonium, and Fabric API to the client's mods folder
6. Start the client and connect to the server

### Expected behavior

After downloading the server's modpack and restarting, the client works as expected

### Actual behavior

After downloading the server's modpack and attempting to restart, the client will crash on startup.

Note that the client will continue to crash on startup if AutoModpack is removed; Fabric API must be redownloaded to resolve the crashing.

### Relevant logs

https://mclo.gs/RsUNJ7v

### Minecraft & Mod Loader versions

1.21 fabric 0.16.0

### Operating system

Windows 10

### AutoModpack version

4.0.0-beta11

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Hey, could you try with fabric loader 0.15.11?

**Comment by Skidamek** [comment]
After a little digging i see that its because Charmonium provides outdated `night-config` packages specifically version 3.6.6 but forgeconfigapiport depends on the same `night-config` packages but with version 3.8.0 and because Charmonium is in default mods dir, older packages are loaded first, and then for some reason they are not getting replaced by the new ones. (automodpack should somehow handle that) 

So when PassthroughSigns is getting initialized it calls forgeconfigapiport which then calls methods from night-config which doesn't even exist yet in the older version which causes game to crash. For the time being easiest solution is to recompile Charmonium for it to provide newer version of night-config to fix the crash. I've created [pull request](https://github.com/svenhjol/Charmonium/pull/72) to do that and also since it has MIT license I've uploaded compiled one to my [proton drive](https://drive.proton.me/urls/H6621E5QCG#0TOWeDW04F6a)

**Comment by SirOaken** [comment]
This is also an issue on Forge 1.20.1

**Comment by DuskCrow19** [comment]
Hello, so for the last few days, i got issue, that looks like that has been a recurring  problem "how automodpack loads certain mods", i have a server where ive been tweaking with several mods, like a lot, but in the last batch i installed the sinytra connector mod crashes, i first thought it was the connector bug, and i went to their github but couldn't find a fix, so i made two instances of the client side, one with the automodpack and one without it, well without the automodpack the game ran smoothly, but with the automodpack same error "Connector Error no existing paths: [ Forge 1.20.1.jar]", using forge 47.3.0, minecraft 1.20.1 and automodpack AutoModpack 4.0.0-beta14 forge, it the worst cases the mods working sinytra are merely client side and visual enhancements, i think (i haven't tested it) i saw that you can disable automodpack on client so you can join the server (obviously having the same matching mods) but only on fabric?, thats the only way i can think to at least fix this kinda bug, i ve read that is kinda more complicated on forge for the way it is coded

**Comment by Skidamek** [comment]
Huh connector error? That's seems different, could you create a new issue and provide a log please?

> i saw that you can disable automodpack on client so you can join the server (obviously having the same matching mods) but only on fabric?

Sorry that's completely wrong, thanks for bringing it to my attention, updated wiki, it should work perfectly fine also on forge.

**Comment by abuyazid955** [comment]
hello, i have the same issues, when i put my mods on the mods folder as a client, the launcher crashed

![image](https://github.com/user-attachments/assets/fd23c970-10c7-4609-ae51-bffe555984c3)

**Comment by Mentalgen** [comment]
Has there been any progress regarding this? I presume there isn't a way to have multiple versions of a dep loaded for a mod so they don't fail on load.

**Comment by Skidamek** [comment]
@Mentalgen  No, i will work on this when i get some more free time.

What it requires to work is to add more logic to my [mod de-duplication code](https://github.com/Skidamek/AutoModpack/blob/7eb74cf24d770426aec1f47be7dd6b716ae1494d/loader/core/src/main/java/pl/skidam/automodpack_loader_core/client/ModpackUtils.java#L84-L232) right now it only checks if there's mod which has the same mod id in the modpack and if so, we remove it from default mods, accounting to not remove client side deps.

It should check if modpack mods are dependent on any mod in the default mods folder and if so, then check if the that dependency version is lower than required/provided by modpack mod. if so then force move that modpack mod to the default mods folder (and add that mod to the ) or extract just that dependency.

Everyone is welcome to make pull request with that changes to speed up fixing it!

**Comment by suerion** [comment]
Hey @Skidamek had now the same Issue on Farmers Delight and Aether. with Automodpack it crash, without Automodpack, it does not Crash the client anymore.

you could look on the issues here
https://github.com/MehVahdJukaar/FarmersDelightRefabricated/issues/107
https://github.com/The-Aether-Team/The-Aether/issues/2379

**Comment by Skidamek** [comment]
@suerion please try [this build](https://github.com/Skidamek/AutoModpack/actions/runs/11869807660) now it should not crash but if you encounter a boot loop (which is very possible) please send your client log and your automodpack-content.json file.

**Comment by suerion** [comment]
[latest.log](https://github.com/user-attachments/files/17784591/latest.log)
[automodpack-content.json](https://github.com/user-attachments/files/17784593/automodpack-content.json)

**Comment by Skidamek** [comment]
Okay, forgot to account for built-in loader mods like mixinextras. Try [that one](https://github.com/Skidamek/AutoModpack/actions/runs/11870419233)

**Comment by suerion** [comment]
Okey, i had looked again on the Files, 
Log file does not include exceptions, that the client gives, but the client started not anymore yet


[latest.log](https://github.com/user-attachments/files/17786744/latest.log)

Here the Client Logger:
![image](https://github.com/user-attachments/assets/1f0ac9ec-a2d8-4d38-813f-5f0efe388ee8)
![image](https://github.com/user-attachments/assets/437770ab-00d9-4424-9f16-3765efcbe34a)
![image](https://github.com/user-attachments/assets/a25d2495-5016-486e-8590-a974d027e18c)

**Comment by suerion** [comment]
Tried to start e few times,
[latest.log](https://github.com/user-attachments/files/17786749/latest.log)

**Comment by suerion** [comment]
Tested, to delete automodpack-content.json and regenerate it with server new.

Deleted all Cached files on Client: (Clean Client)

Latest (automodpack-content.json should not up to date but is on latest?
[latest.log](https://github.com/user-attachments/files/17786771/latest.log)

Now i delete also the whole Modpack in the Modpacks folder  logs will come after testing

**Comment by suerion** [comment]
I think yet are the librarys or fabric api not moved any more and a lot of mods moved without needed...

[2024-11-16-1.log](https://github.com/user-attachments/files/17786904/2024-11-16-1.log)
[latest.log](https://github.com/user-attachments/files/17786903/latest.log)

**Comment by suerion** [comment]
Generated from Server:
[automodpack-content.json](https://github.com/user-attachments/files/17786920/automodpack-content.json)
On Client Side:
[automodpack-content.json](https://github.com/user-attachments/files/17786923/automodpack-content.json)

**Comment by Skidamek** [comment]
woah i dont need that deep testing, log is enough thanks. if you willing to spend more time testing [next build](https://github.com/Skidamek/AutoModpack/actions/runs/11871207792) is for you lol

**Comment by suerion** [comment]
Trying allways, deep test :) if something could also fix ;)

**Comment by suerion** [comment]
Had again the issue, that Minecraft loaded in Vanilla Minecraft after issue with File movement on first start
[latest.log](https://github.com/user-attachments/files/17787053/latest.log)

![image](https://github.com/user-attachments/assets/49c499ad-d60b-4732-bb7d-2cc3014a7a56)
![image](https://github.com/user-attachments/assets/f60e708b-04ef-478a-bd41-22b96bc9b2a2)
![image](https://github.com/user-attachments/assets/a142c359-9821-4b6b-bf95-1784d8174cd0)


second Start -> again start in Vanilla Minecraft
[latest.log](https://github.com/user-attachments/files/17787073/latest.log)
![image](https://github.com/user-attachments/assets/8f7507b6-d115-4b08-9106-d46876e5c76e)
![image](https://github.com/user-attachments/assets/f40fa337-8b31-4fed-8295-7e5617e18074)

Cleared Cache and all and it is again the same issue

**Comment by suerion** [comment]
But, it has loaded only the disabled files ;) the file movement is right now

**Comment by suerion** [comment]
The issue with the crash from automodpack is fixed again, but, now it crash again on Mixin Inject
[latest.log](https://github.com/user-attachments/files/17787932/latest.log)

**Comment by Skidamek** [comment]
Should be fixed at least on fabric right now. If anyone wants to test [go ahead](https://github.com/Skidamek/AutoModpack/actions/runs/11976130289)

**Comment by Kamaad1** [comment]
Is there a release with a fix for this available?

**Comment by suerion** [comment]
@Kamaad1 we are working and debuging right now on the fixes, and there will be an release, if it does work

**Comment by Skidamek** [comment]
@Kamaad1 dev build 99% fixes the issue, would be awesome to also get your feedback you can download build from [there](https://github.com/Skidamek/AutoModpack/actions/runs/11981407383). We with @suerion tested and it seem to work pretty well now (if you are on fabric - but forge feedback would be also welcome). If everything goes well beta 19 with the fix is expected to be released tomorrow.

**Comment by Skidamek** [comment]
Fixed in beta 19. If someone is still encounters this on neo/forge please open new issue.
