### ISSUE TITLE
Editable files should be copied into the client's modpack folder to preserve their state when switching modpacks

### ISSUE THREAD

**Issue by n-zer** [Skidamek/AutoModpack#257]
### Motivation

Currently, when you switch modpacks any editable files (such as config, options.txt, etc.) are overwritten with the data from the new modpack. This makes using editable files for config basically useless if the player is playing on multiple servers using automodpack. Or if, as in my case, you're moving your server to a new host.

### Description

When an editable file is edited, its new content should be copied into the modpack folder, and the file should not be downloaded under any circumstances as long as it already exists in the modpack folder. This would allow changes to editable files to be preserved when switching back and forth between several modpacks.

**Comment by Skidamek** [comment]
Beta 12

**Comment by Skidamek** [comment]
Do note that editable files are copied to the modpack directory only when modpack switch happens
