### ISSUE TITLE
Modpack URLs in automodpack-client.json are not updated when connecting to a server using the same modpack

### ISSUE THREAD

**Issue by n-zer** [Skidamek/AutoModpack#258]
### Bug description

When moving a server to a new host (and thus a new IP address), the modpack name will remain the same, but the URL in automodpack-client.json will not be updated with the new address. This can cause two issues:

* Fetching mods at startup will be broken if the server is not online at the old IP
* If the server is online at both locations and the modpack differs in any way, clients will not be able to enter the new server. The old modpack will be fetched at startup, the new one will be fetched when joining the new server and the user will be prompted to restart, and this will repeat.

This feels like something that is intended to work, based on the fact that the IP is not appended to `selectedModpack`.

### Steps to reproduce

1. Connect to a server using automodpack
2. Download the modpack and restart
3. Connect to a different server using automodpack, whose modpack has the same name

### Expected behavior

Everything behaves as if the modpack did not change, and the URL in automodpack-client.json is automatically updated to the new server's modpack hosting address.

### Actual behavior

If the old server is offline, updating the modpack on startup is broken. If the old server is online and there are any modpack differences between the servers, the user will be prompted to update the modpack every time they attempt to join the new server.

### Minecraft & Mod Loader versions

1.21 fabric 0.16.0

### Operating system

Windows 10

### AutoModpack version

4.0.0-beta11

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Wow that's a lot of reports thanks, I will try to sort them out quickly

**Comment by Skidamek** [comment]
Not sure if this commit will fix this, needs testing

**Comment by Skidamek** [comment]
Now it is fixed.
Gonna close when published.

**Comment by Skidamek** [comment]
Do note, that if modpack has the same name as the previous then the previous modpack will be overwritten

**Comment by Skidamek** [comment]
Yeah I just meant that there won't be any copy of the previous originally installed modpack.
It will reuse all files that there are.

**Comment by Skidamek** [comment]
Beta 12
