### ISSUE TITLE
Version Mismatch Problem

### ISSUE THREAD

**Issue by harmanprecious** [Skidamek/AutoModpack#259]
### Bug description

![image](https://github.com/user-attachments/assets/da50d019-fb98-458d-8d32-6aff85edc711)
![image](https://github.com/user-attachments/assets/5889d142-9d7f-495b-b156-374db688ad23)
![image](https://github.com/user-attachments/assets/5b942e73-13ef-403e-b257-7b5d3e585862)

I'm getting this error.

### Steps to reproduce

1. I downloaded mod to my pc and server
2. I restarted server
3. I got this error
4. I tried shut down server and remove all automod files with configs or smth
5. I did everything again
still same

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.92.2

### Minecraft launcher

Modrinth

### Operating system

Windows 11

### AutoModpack version

4.0.0-beta11

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Please provide relevant logs from client and server

**Comment by Skidamek** [comment]
stale
