### ISSUE TITLE
Editable files are working incorrectly again - Can't synchronize the options.txt file for the first time

### ISSUE THREAD

**Issue by jorge77401** [Skidamek/AutoModpack#263]
### Bug description

First of all, I want to thank you for this wonderful mod. In the tests I've been doing, it works perfectly and saves a lot of time; however, I have a small problem, though I believe it might be my fault and something I'm doing wrong. I'm trying to sync the "options.txt" file as an editable file, obviously. The idea is that the client downloads the file and can have options like language, keyboard shortcuts, resource pack configurations, etc., in a "basic" state so that all players have more or less the same settings.

However, once the file is downloaded, it is replaced by the original Minecraft file, and all these settings are lost.

I am placing the file inside the Main folder of the mod on the server. What am I doing wrong?

### Steps to reproduce

1. Copy the file with the pre-set adjustments into the Main folder of the modpack.
2. Create a new Minecraft installation with only Automodpack activated and connect to the server.
3. Wait for it to download all the files, and then reopen the game.

### Expected behavior

Entiendo que  los ajsutes pre-establecidos en el archivo del servidor deberían verse reflejados en el cliente

### Actual behavior

Actually, the vanilla Minecraft file is being used, and it is automatically placed in the Automatic Modpack folder.

### Minecraft & Mod Loader versions

1.20.1 Forge 47.3.0

### Minecraft launcher

Multi MC

### Operating system

Windows 10

### AutoModpack version

Beta 12

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Could you check please if it works on beta 11?

**Comment by jorge77401** [comment]
I can confirm that everything works as expected in Beta 11, however, I will continue testing; thank you very much.

**Comment by Skidamek** [comment]
Can't reproduce, works as intended.

**Comment by Skidamek** [comment]
see #249 if it doesn't works like so open a new issue please
