### ISSUE TITLE
1.20.1 version is compiled with Java 21 (must be 17)

### ISSUE THREAD

**Issue by Whitebrim** [Skidamek/AutoModpack#264]
### Bug description

Minecraft 1.20.1 need Java 17 to run.
Latest beta release for 1.20.1 is compiled using Java 21 and can't be run with Java 17.

### Steps to reproduce

--//--

### Minecraft & Mod Loader versions

1.20.1 fabric

### Operating system

Windows 11

### AutoModpack version

4.0.0-beta12

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Its not just 1.20.1 see #261 it's all fabric, please test dev build attached
