### ISSUE TITLE
Crash after downloading mods from server

### ISSUE THREAD

**Issue by GalvareyPoco** [Skidamek/AutoModpack#267]
### Bug description

i have a fresh new server, but everytime my client downloads items from the server it downloads and when it ask to restart minecraft if crashes i am using a server 1.21.1 andclient 1.21.1 with a fresh server install all with fabric
[latest.log](https://github.com/user-attachments/files/16669024/latest.log)
[automodpack-content.json](https://github.com/user-attachments/files/16669026/automodpack-content.json)

### Steps to reproduce

it is a fresh server

### Expected behavior

continue to play

### Actual behavior

game crashes when opening after automodpack ask to restart the game

### Minecraft & Mod Loader versions

1.21.1 fabric 0.16.2

### Minecraft launcher

minecraft launcher

### Operating system

windows 11

### AutoModpack version

1.21.1-fabric-4.0.0-beta14

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Its due to changes made in fabric loader 0.16.1, patched in beta 15

**Comment by GalvareyPoco** [comment]
still having the same issue @Skidamek updated to beta 15 on server and client

[latest.log](https://github.com/user-attachments/files/16677239/latest.log)

**Comment by Skidamek** [comment]
whoops its a different issue tho

**Comment by GalvareyPoco** [comment]
seems to be wokring correctly now, thanks
