### ISSUE TITLE
Mixing transformation fail with Sounds

### ISSUE THREAD

**Issue by Mentalgen** [Skidamek/AutoModpack#272]
### Bug description

I'm having trouble trying to figure this out bug out...seems like when Sounds and MRU got updated from version 1.1.5 to 2.0.0 and 0.4.5 to 1.0.0 respectively, AutoModpack is unable to load these mods alongside other ones. These mods  _can_ load when not in the modpack folder for some reason, I'm not sure why this is or what mods might be conflicting. Would appreciate help in debugging this.

### Steps to reproduce

Make a modpack that includes the latest versions of MRU or Sounds, and try running on the client. (I think this works fine however, seems to be only with my modpack.

### Expected behavior

Game starts and boots to a main menu

### Actual behavior

Game crashes on initialization.

### Relevant logs

With Sounds and MRU in actual mods folder: https://mclo.gs/1XhKooS
With Sounds and MRU in the modpack folder: https://mclo.gs/f5C4KqY

### Minecraft & Mod Loader versions

Minecraft 1.20.1 with Fabric 0.15.11

### Minecraft launcher

PolyMC

### Operating system

Garuda Linux

### AutoModpack version

4.0.0-beta16

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
I see it's #255 related. But in this case aitomodpack bundles mixin extras 0.3.6 while sounds bundles 0.5.x using its features, but loader loads the first version of this module so the 0.5.x features which sounds requires don't exists.

I have an idea how could I fix it, I will work on it tomorrow.

**Comment by Mentalgen** [comment]
Copy, appreciate it.

PS: MCA is not spawning tombstones where villagers actually die, I've been seeing them thrown down into the bottom of the world and it's getting annoying for the peeps on my server lol. Using Xray to not need to explore for god knows how long.
