### ISSUE TITLE
Minecraft crashes on launch when using Automodpack. (FABRIC 1.20.1)

### ISSUE THREAD

**Issue by MinoreMin** [Skidamek/AutoModpack#273]
### Bug description

I'm hosting a fabric (0.15.11) (1.20.1) server, with about 243 mods. The server runs fine, but the client version crashes whenever I try to launch the game. 

### Steps to reproduce

Just launch Automodpack after syncing with the server

### Expected behavior

Minecraft launchs and updates the modpack

### Actual behavior

Minecraft crashes before even launching
(I'm using modrinth)

### Relevant logs

https://mclo.gs/fJFW1t5

### Minecraft & Mod Loader versions

1.20.1

### Minecraft launcher

Modrinch

### Operating system

Windows 11

### AutoModpack version

4.0.0 Beta 16 and below

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
#268
