### ISSUE TITLE
Regarding mod download speed

### ISSUE THREAD

**Issue by Lafatalite** [Skidamek/AutoModpack#278]
### Motivation

The maximum download speed in the client is currently only 256kb/s. Is it possible to configure the speed? I experience the same speed even when downloading within the internal network.

### Description

1

**Comment by Skidamek** [comment]
Really? never experienced that one...
There isn't any download speed cap.

**Comment by suerion** [comment]
i had loaded today with 8 MBit/s, could be an issue on Modrinth?

**Comment by Skidamek** [comment]
i have updated broken speed meter code, so it now should more correct values, please try dev build https://github.com/Skidamek/AutoModpack/actions/runs/11084675258

**Comment by Skidamek** [comment]
Should be addressed in beta 19
