### ISSUE TITLE
I can't log into the server

### ISSUE THREAD

**Issue by Sunshine-MC** [Skidamek/AutoModpack#279]
### Bug description

The server had been working stably without my intervention for a week and at some unrelated moment players started getting kicked with the error `[Automodpack] Host server error. Please contact server admiristrator to check the server logs!`. The console displays the following lines 
```
[12:26:50] [Netty Epoll Server IO #5/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
```
sometimes even just like that (without trying to log into the server)
I used the beta16 version but after updating the problem did not go away
[latest.log](https://github.com/user-attachments/files/17005238/latest.1.log)

### Steps to reproduce

gust just wait

### Expected behavior

correct operation of the server

### Minecraft & Mod Loader versions

1.20.1 fabric 0.15.11

### Minecraft launcher

This problem is common for everyone and does not depend on the launcher

### Operating system

like the past

### AutoModpack version

4.0.0-beta16 or 17

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Could you provide your server config file?

**Comment by Sunshine-MC** [comment]
[automodpack-server.json](https://github.com/user-attachments/files/17005620/automodpack-server.json)
Certainly

**Comment by Sunshine-MC** [comment]
I did not order ip and similar information since everyone worked without it

**Comment by Skidamek** [comment]
It might have been fixed in beta 19, need testing.

**Comment by Skidamek** [comment]
Stale and for 99% already fixed, if not please open new issue
