### ISSUE TITLE
MacOS crash.

### ISSUE THREAD

**Issue by KateReller** [Skidamek/AutoModpack#28]
Automodpack crashes on start up.

https://paste.ee/p/2NjNg

**Comment by Skidamek** [comment]
Should be fixed in next release

**Comment by Skidamek** [comment]
> Automodpack crashes on start up.
> 
> https://paste.ee/p/2NjNg

Can you try this? https://github.com/Skidamek/AutoModpack/suites/7294659428/artifacts/294295075

**Comment by KateReller** [comment]
It works.

**Comment by Skidamek** [comment]
so fixed in 2.1.1
