### ISSUE TITLE
can join server with custom config files 

### ISSUE THREAD

**Issue by V7I0SeventhSector** [Skidamek/AutoModpack#280]
### Bug description

my friend joined my server after i updated it with only 1 mod and they got this
"The server you are attempting to connect to has "Enchantment" installed, but you configuration file does not match the server's

Please make sure your configuration files match the server's. 
Your configuration files is located at C:\Users\#NAME\AppData\Roaming\.minecraft\config\enchantment.json.
This is not a bug, do not report."

yes i know it says its not a bug but 1. how not?? and 2. is there a work around??? why can i not modify the config of server side mod?? 

### Steps to reproduce

not entirely sure if it was related to another mod or not but I added "enchantment" mod https://modrinth.com/mod/enchancement 
to my server and modified the config server side so max enchants are set from 1 to 3 after i did this no one was able to enter the server unless they modified there own config and made it match the servers config file. their

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.16.2

### Minecraft launcher

Minecraft Launcher

### Operating system

Windows 10

### AutoModpack version

automodpack-mc1.20.1-fabric-4.0.0-beta16

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
It's not an automodpack issue. If I understand correctly, clients needs matching config of that mod. Then you can just place the config of said mod to ~/automodpack/host-modpack/main/config/<config> as in wiki https://github.com/Skidamek/AutoModpack/wiki/Modpack-Creation

**Comment by V7I0SeventhSector** [comment]
ohh, ok so i can just inable it server side and it will work?? 

also, would it be possible for you to create a Discord for this mod so i dont have to make a report every time i have a problem?

**Comment by Skidamek** [comment]
Yes you can just configure it server side. Discord server is in plans but for the time being you can write directly to me, on wiki page you can find my discord profile, feel write to write.
