### ISSUE TITLE
Restart into Vanilla Loader without Modpack

### ISSUE THREAD

**Issue by suerion** [Skidamek/AutoModpack#281]
### Bug description

Sometimes, it does load after downloaded Modpack into Vanilla Minecraft, could be an Compat Issue with 
https://modrinth.com/mod/mod-loading-screen

### Steps to reproduce

Create Modpack on Server,
Download with Client, 
Try to start load Fabric in Modded
Loaded Vanilla

### Relevant logs

Issue Only on Client Logger:

![image](https://github.com/user-attachments/assets/9d40237c-571a-4cd9-a9bd-c6c289595d86)
![image](https://github.com/user-attachments/assets/fff30ae6-0867-4910-b231-e37d51a582a9)
![image](https://github.com/user-attachments/assets/5aac51ee-c95b-4218-8edf-54af3ea8563c)
![image](https://github.com/user-attachments/assets/3950ff79-cab8-41a1-82ae-894d279e4bae)

Here the Log ->
https://mclo.gs/pzfiTFn

Need to Restart, to get into Modded Minecraft
![image](https://github.com/user-attachments/assets/98fe4e59-f4da-4391-af0c-a70d3b887e58)

### Minecraft & Mod Loader versions

1.21.1 Fabric 0.16.5

### Minecraft launcher

Curseforge, Vanilla and MultiMC

### Operating system

Windows 11

### AutoModpack version

Beta 17, not tested in Beta 18

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by suerion** [comment]
[latest.log](https://github.com/user-attachments/files/17179307/latest.log)
Here the actuall latest.log

**Comment by suerion** [comment]
Minecraft Launcher Logger (not all logged in latest.log
![image](https://github.com/user-attachments/assets/779f0686-8461-4553-8635-08f3f8707ab7)
![image](https://github.com/user-attachments/assets/e4c5ecc3-bd8f-47fa-8c82-9039e2bf7bae)
![image](https://github.com/user-attachments/assets/e92d9ec1-8111-458d-95ce-72ed79a158d3)

**Comment by Skidamek** [comment]
it may have been fixed in beta 19, need testing

**Comment by suerion** [comment]
will look on testing ;)

**Comment by suerion** [comment]
Had this issue not anymore, since the Modloader looks on neesting needed mods, it trys to start not anymore in vanilla enviroment.

Willl test a little bit more, but looks nice

**Comment by Skidamek** [comment]
closing then
