### ISSUE TITLE
unable to join any minecraft server after i download mods from my server

### ISSUE THREAD

**Issue by V7I0SeventhSector** [Skidamek/AutoModpack#282]
### Bug description

i didnt do anything, i was on my server doing just fine, i loged out to go too sleep and when i got back on later i could not rejoin, other players could join no problem and i had NOT added any mods or changed anything about Minecraft in any way. 
the ONLY thing that did happen is i restarted my PC and when i did that Windows updated. 
i tried removing ALL mods and reinstalling them, nothing. 
i tried updated the mod from B16 to B18, nothing. 
i tried going through the mods one at a time, still nothing. 
im not entirly sure if it even is this mod or not as i cant figure this out, it gives different errors on what seems to be random. . .

"Joining world..." 
thats where it stops, after a long time it might pop up with an error but it can take upto 10-20 min for that to pop up IF it even does. 

that being said some of the errors ive seen are
"Unable to connect to lobby: Failed to load profile in time, please reconnect. 
If this continues to happen, contact server admin."
"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16402) + length(1) exceeds writerIndex(16402): UnpooledHeapByteBuf(ridx:16402, widx: 16402, cap: 16402/16402)

### Steps to reproduce

1. download my modpack
2. install onto a server
3. try and join the server with no mods on the MC/fabric version stated below. 

IF this dose NOT work for you please let me know. . . 
im going to try and reinstall Minecraft next. . 

### Relevant logs

Client Latest logs: https://mclo.gs/BbFxyDF
Client Logs: https://mclo.gs/iimliNQ
Server Logs: https://mclo.gs/RnlcPVP

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.16.2

### Minecraft launcher

Minecraft Launcher

### Operating system

windows 10

### AutoModpack version

automodpack-mc1.20.1-fabric-4.0.0-beta18

### Other information

unable to supply mod pack as its too large. 
i can supply through other means if requested. 

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Try to add packet fixer mod https://modrinth.com/mod/packet-fixer
Or remove worlds_together mod 

[Render thread/ERROR]: [worlds_together] Tried to read from global registry!

**Comment by Skidamek** [comment]
Is this still the issue? any update?

**Comment by V7I0SeventhSector** [comment]
oh, it was fixed, sorry!!
i added the mod and redownloaded all the mods from the server NOT using Automodpack and it worked after that. 

for some reason, the problem was being caused when i downloaded the mode from the server but it was ONLY me haveing this problem? 
so idk what happen. . . but its working now.
