### ISSUE TITLE
deletes most mods

### ISSUE THREAD

**Issue by StillMars** [Skidamek/AutoModpack#284]
### Bug description

when i try to join my server it deletes most of all my mods on the client side

### Steps to reproduce

download auto modpack to craftoria both server and client side
launch both
join the server
will ask to download mods (although it has all the mods the server does nothing new besides automodpack)
will ask to restart game
then check the mods it downloaded and now all the other mods are gone

### Expected behavior

to join the server without having to do anything

### Actual behavior

deletes most mods in the mods folder besides the ones it wanted to download

### Relevant logs

[debug.log](https://github.com/user-attachments/files/17142139/debug.log)
[latest.log](https://github.com/user-attachments/files/17142140/latest.log)

### Minecraft & Mod Loader versions

1.21.1 neoforge 21.1.58

### Minecraft launcher

minecraft launcher

### Operating system

windows 11

### AutoModpack version

4.0.0 beta 18

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
That's intended, have you try launching the game "without" mods?

**Comment by Skidamek** [comment]
Read it https://github.com/Skidamek/AutoModpack/wiki/File-Structure-&-Logic#client

**Comment by StillMars** [comment]
after some more investigation i noticed that "+" was replaced with "%2b" on the server side mod names automodpack did not cause that. although is seems like automodpack recognized where the mods came from and put them in the correct place but left the "%2b" mods where they where and thus there was duplicate mods which crashed the client game on start.

after fixing the mod names it works correctly now reason for creating a issue post was because i had this problem a long time ago with BMC4 and could not figure out the problem so i when without automodpack until the problem i was running into was figured out.

now that i know what the problem was it could have been the same one from back then

**Comment by Skidamek** [comment]
Wait so do you still have any issue or what? I am not sure if I understand you, where were these "+"s you are talking about?

**Comment by StillMars** [comment]
issue has been fixed
for example:
server side mod name "chattoggle-5.0.1%2b1.21-neoforge.jar"
client side mod name "chattoggle-5.0.1+1.21-neoforge.jar"
automodpack seemed to have recognized its as a mod and the correct mod even though it had a different name (client side)
what i think happened was it saw it as the correct mod but named differently so it downloaded it again with the correct name and kept the wrongly name one in place thus having dupped mods (client side)
