### ISSUE TITLE
Prevent out of server resource packs from joining.

### ISSUE THREAD

**Issue by Paper319** [Skidamek/AutoModpack#286]
### Motivation

So I have a modded server and anti xray is something Id like. Sadly the mod I use crashed the client in some area, embedium issue i think.

### Description

Since synced and allowed files doesn't monitor folders I cant prevent resource packs aka xray ones not from being added to the client.

**Comment by Skidamek** [comment]
See #131 
However do note that threes no way to force prevent players to not cheat, it just not possible, you would need to have direct access to players computers, even anti cheats to games like fortnite running on kernel level can be workarounded.
