### ISSUE TITLE
Incompatibility with auditory continued for 1.21

### ISSUE THREAD

**Issue by Danszerlied** [Skidamek/AutoModpack#287]
### Bug description

Auditory continued does not seem to work when automodpack installed it. If auditory was in the normal mods folder it works. But not under the automodpack folder. A fix to this is to have an option to be able to put some mods in the normal mod folder and not automodpack's if thats possible

### Steps to reproduce

Create a server with automodpack
Put auditory in either server mods or automodpack mods (same result)

### Expected behavior

Block sounds should work

### Actual behavior

no sounds

### Minecraft & Mod Loader versions

Fabric 1.21 0.16.5

### Minecraft launcher

ATLauncher

### Operating system

Windows 11

### AutoModpack version

4.0.0

### Other information

auditory config does not work on servers in any version when it's under automodpack folder

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
What do you mean by "it doesnt seem to work"? does it crash? or it doesnt load into the game? could you provide log from client?

**Comment by Danszerlied** [comment]
it doesnt crash my game, i'm able to load but the mod acts like its not there
[log.txt](https://github.com/user-attachments/files/17246150/log.txt)

**Comment by Skidamek** [comment]
how does it acts like its not there? install mod menu, it is there, i see in logs that it is loaded perfectly fine

**Comment by Danszerlied** [comment]
No what i'm saying is auditory does not work when installed by automodpack. the mod loaded but the sounds dont play from auditory. it only works on singleplayer for some reason

**Comment by Skidamek** [comment]
AutoModpack does not interfere with how mods work in multiplayer. If a mod works in singleplayer when loaded by AutoModpack, it means the issue is not with AutoModpack. For multiplayer issues, please report them to the Audiatory.
