### ISSUE TITLE
Crashing on Dedicated Server

### ISSUE THREAD

**Issue by hideki2k02** [Skidamek/AutoModpack#291]
### Bug description

Hello, recently I've discovered AutoModpack and I was really fascinated about its ideas, so I've started testing AutoModpack to deploy it on my server. On a Local Environment it worked flawlessly so far, but after testing it on a production environment it crashes.

### Steps to reproduce

1. Add the modpack to a dedicated server (CloudNord)
2. Launch the server
3. It should crash

### Expected behavior

The server should launch without any major implications

### Actual behavior

The server crashed with an error that is difficult to pinpoint what exactly caused it

### Relevant logs

https://mclo.gs/P206RrU

### Minecraft & Mod Loader versions

1.20.1 Fabric 0.16.5

### Minecraft launcher

Prism Launcher

### Operating system

Dedicated Server

### AutoModpack version

4.0.0 Beta 18

### Other information

server config:
```js
{
  "DO_NOT_CHANGE_IT": 1,
  "modpackName": "The Createville Refab",
  "modpackHost": true,
  "generateModpackOnStart": true,
  "syncedFiles": [
    "/mods/*.jar",
    "!/kubejs",
    "!/world",
  ],
  "allowEditsInFiles": [
    "/options.txt",
    "/config/*",
  ],
  "autoExcludeUnnecessaryFiles": true,
  "requireAutoModpackOnClient": false,
  "nagUnModdedClients": true,
  "nagMessage": "This server provides dedicated modpack through AutoModpack!",
  "nagClickableMessage": "Click here to get the AutoModpack!",
  "nagClickableLink": "https://modrinth.com/project/automodpack",
  "autoExcludeServerSideMods": true,
  "hostModpackOnMinecraftPort": true,
  "hostIp": "",
  "hostLocalIp": "",
  "updateIpsOnEveryStart": false,
  "hostPort": -1,
  "reverseProxy": false,
  "selfUpdater": true,
  "acceptedLoaders": [
    "fabric"
  ]
}
```

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Hey, please try to change in syncedFiles `!/kubejs` to `!/kubejs/*` and `!/world` to `!/world/*`

**Comment by hideki2k02** [comment]
Turns out my error was not related to that but a corruption in the config files... XD
