### ISSUE TITLE
Feather client Restart your game 

### ISSUE THREAD

**Issue by Trayzers** [Skidamek/AutoModpack#295]
### Bug description

![image](https://github.com/user-attachments/assets/17782512-6e7e-4ccf-abeb-003486e1f1f0)

works fine on curseforge but I like using feather client because it has the server hosting and I just like the features.
Disabled everything except amp and it still gives me that.

### Steps to reproduce

Installed automodpack
Downloaded the server mods
told me to restart, Restarted
and now we are here with the infinite restart your game.

### Expected behavior

just restart once after it "updated" succesfully

### Actual behavior

Pressed ok and when pressing 
![image](https://github.com/user-attachments/assets/65ce669d-ff46-46b3-9027-c8150a24f28e)
It just tells me
![image](https://github.com/user-attachments/assets/2f65fd0d-5980-4f3f-aaef-ccc48ae0bad7)

### Relevant logs

Idk what log I should be pasting here as it seems to be a client issue.

### Minecraft & Mod Loader versions

Fabric 1.21

### Minecraft launcher

Feather client

### Operating system

Windows 10 pro

### AutoModpack version

4.0.0-beta18

### Other information

Works when launching from Curseforge, Doesn't work when launching from feather client

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Yeah feather client is unsupported as long as they are modifying internals of fabric loader

**Comment by Skidamek** [comment]
Give me source code to their modifications then we can talk

**Comment by Skidamek** [comment]
For now i encourage you to use free and open sources [alternatives](https://microcontrollersdev.github.io/Alternatives/latest/feather/)

**Comment by Trayzers** [comment]
> For now i encourage you to use free and open sources [alternatives](https://microcontrollersdev.github.io/Alternatives/latest/feather/)

Will do thanks for giving me the link
