### ISSUE TITLE
[1.20.1-Forge] [Change Items Durability Mod] | Even though I set the mode setting in the config file on the server, it is not updated on the client.

### ISSUE THREAD

**Issue by TeQTabanca** [Skidamek/AutoModpack#298]
### Bug description

Even though I set the mode setting in the config file on the server, it is not updated on the client.

### Steps to reproduce

1. Download [Change Items Durability Mod](https://www.curseforge.com/minecraft/mc-mods/change-items-durability/download/4962882)
2. There is changeitemsdurability.conf file inside the server config file, by default shield item durability is set to 5. Set its durability to 100 or 1000 and save.
3. Start the server and check the durability of the shield item.

### Expected behavior

The changeitemsdurability.conf file needs to be updated according to the server.

### Minecraft & Mod Loader versions

1.20.1-47.3.11

### Operating system

Windows 11

### AutoModpack version

automodpack-mc1.20.1-forge-4.0.0-beta18

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Skidamek** [comment]
Please test if this issue exists if you remove automodpack from your server. If it does please send your automodpack-content.json file and latest related logs from client and sever.

**Comment by TeQTabanca** [comment]
> Please test if this issue exists if you remove automodpack from your server. If it does, report to them, if it does not please send your automodpack-content.json file and latest related logs from client and sever.

The problem still persists.

[automodpack-content.json](https://github.com/user-attachments/files/17786740/automodpack-content.json)

[Logs](https://mclo.gs/t4jKJmU)

**Comment by suerion** [comment]
is the config file in an folder? or where is it?

**Comment by TeQTabanca** [comment]
> is the config file in an folder? or where is it?

in config file

**Comment by suerion** [comment]
@TeQTabanca where is the server? did you have the server on windows 11? or is this in an dedicated server?

**Comment by TeQTabanca** [comment]
> @TeQTabanca where is the server? did you have the server on windows 11? or is this in an dedicated server?

I'm testing on Windows 11

**Comment by suerion** [comment]
Change the config file, and try to delete automodpack-content.json. in the servers automodpack folder

After this, send please the new generatet automodpack-content file, then, try to connect with client, and see if the config is changed in /automodpack/host...../config/

**Comment by TeQTabanca** [comment]
> Change the config file, and try to delete automodpack-content.json. in the servers automodpack folder
> 
> After this, send please the new generatet automodpack-content file, then, try to connect with client, and see if the config is changed in /automodpack/host...../config/

Automodpack is trying to update but the problem still persists because the config file is in the main config.

**Comment by suerion** [comment]
Okey, 

```
    {
      "file": "/config/changeitemsdurability.conf",
      "size": "100",
      "type": "config",
      "editable": true,
      "sha1": "15ff29587d5a06490115c2c095ab9ff95abaf451",
      "murmur": null
    }
```

Did you have the latest log from the client? because it will try to change the config. but something went wrong.

and send also please the automodpack-server.json from the server

i think we will find the issue ;)

**Comment by Skidamek** [comment]
But according to that mod curseforge page, that mod allows you to change tool durability server side, you don't need sync server config to client, you only just need to make sure you have that mod on client and on server. If it doesn't work like so, report to them

**Comment by TeQTabanca** [comment]
> Okey,
> 
> ```
>     {
>       "file": "/config/changeitemsdurability.conf",
>       "size": "100",
>       "type": "config",
>       "editable": true,
>       "sha1": "15ff29587d5a06490115c2c095ab9ff95abaf451",
>       "murmur": null
>     }
> ```
> 
> Did you have the latest log from the client? because it will try to change the config. but something went wrong.
> 
> and send also please the automodpack-server.json from the server
> 
> i think we will find the issue ;)
> 
> Did you close also the Launcher or only Minecraft?

[automodpack-server.json](https://github.com/user-attachments/files/17787282/automodpack-server.json)

Client [log](https://mclo.gs/RYg0aZX)

**Comment by TeQTabanca** [comment]
> But according to that mod curseforge page, that mod allows you to change tool durability server side, you don't need sync server config to client, you only just need to make sure you have that mod on client and on server. If it doesn't work like so, report to them

The problem is when it is not updated the item drops to -value and is not deleted from the inventory.

**Comment by TeQTabanca** [comment]
I looked for such mods but couldn't find any. There is a synchronization problem in this mode, AutomodPack mode also has a synchronization feature, but I think it cannot update the .conf files.

**Comment by Skidamek** [comment]
It can, automodpack can update anything actually

**Comment by suerion** [comment]
> > But according to that mod curseforge page, that mod allows you to change tool durability server side, you don't need sync server config to client, you only just need to make sure you have that mod on client and on server. If it doesn't work like so, report to them
> 
> 
> 
> The problem is when it is not updated the item drops to -value and is not deleted from the inventory.

On Client
Try to delete in the automodpack/host/

The complete folder of the hosted modpack and try to download it again, important is, that you delete automodpack_content.json

And then send first modpack update  latest.log and then send after starting minecraft the latest.log

If there is a issue on syncing the config file.


But as Skidam writed, it does not need the config on client side

**Comment by Skidamek** [comment]
Remove /config/* form editable files, that will make sure to have all of your configs always synced to the sever version

**Comment by suerion** [comment]
Yeah thats the issue, because it is there already, 

It does not overwrite the config anymore becaus all config files are editable, 

If there was no config file there, it does sync the file from server.

Then, this brings me to an sugfestion @Skidamek could you add an option to download on first sync and then it is editable? 

Because i will send options.txt to the clients. And it should editable. Could there an option, to overwrite some files and rhen it should be editable?

**Comment by Skidamek** [comment]
> Then, this brings me to an sugfestion @Skidamek could you add an option to download on first sync and then it is editable?
Because i will send options.txt to the clients. And it should editable. Could there an option, to overwrite some files and rhen it should be editable?

That's how it should work, you sure it doesn't do it already? I remember fixing it like half a year ago to achieve that behavior. If it's broken please create new issue.

**Comment by TeQTabanca** [comment]
> > > But according to that mod curseforge page, that mod allows you to change tool durability server side, you don't need sync server config to client, you only just need to make sure you have that mod on client and on server. If it doesn't work like so, report to them
> > 
> > 
> > The problem is when it is not updated the item drops to -value and is not deleted from the inventory.
> 
> On Client Try to delete in the automodpack/host/
> 
> The complete folder of the hosted modpack and try to download it again, important is, that you delete automodpack_content.json
> 
> And then send first modpack update latest.log and then send after starting minecraft the latest.log
> 
> If there is a issue on syncing the config file.
> 
> But as Skidam writed, it does not need the config on client side

Client [Log](https://mclo.gs/4EI7bJj)

**Comment by TeQTabanca** [comment]
> Remove `/config/*` form editable files, that will make sure to have all of your configs always synced to the sever version

I tried and still have the same problem.

**Comment by suerion** [comment]
> > Remove `/config/*` form editable files, that will make sure to have all of your configs always synced to the sever version
> 
> 
> 
> I tried and still have the same problem.

On your client log, it shows this

[16Kas2024 20:56:34.852] [main/INFO] [AutoModpack/]: Overwriting /config/changeitemsdurability.conf file to the modpack version

Try to look again on your server, if you had changed the config there, 

Or send me your server setup to see whats your problem?

(Zip file on wetransfer or something)

I will check it here.

It looks like it should work

What i need: on server automodpack, config and mods folder

**Comment by TeQTabanca** [comment]
> > > Remove `/config/*` form editable files, that will make sure to have all of your configs always synced to the sever version
> > 
> > 
> > I tried and still have the same problem.
> 
> On your client log, it shows this
> 
> [16Kas2024 20:56:34.852] [main/INFO] [AutoModpack/]: Overwriting /config/changeitemsdurability.conf file to the modpack version
> 
> Try to look again on your server, if you had changed the config there,
> 
> Or send me your server setup to see whats your problem?
> 
> (Zip file on wetransfer or something)
> 
> I will check it here.
> 
> It looks like it should work
> 
> What i need: on server automodpack, config and mods folder

[1.20.1-Forge.zip](https://github.com/user-attachments/files/17787624/1.20.1-Forge.zip)

**Comment by suerion** [comment]
![image](https://github.com/user-attachments/assets/2dc22ea7-95f9-49e6-a375-aafb8c5251d4)
You don't need the folder,  delete it, in this folder there is the config file, that file overwrite the config files again


[automodpack-server.json](https://github.com/user-attachments/files/17787717/automodpack-server.json)
Use this Automodpack setting, it sync the complet config folder from server config
```
  "syncedFiles": [
    "/mods/*.jar",
    "/config/*",
    "!/mods/iDontWantThisModInModpack.jar",
    "!/config/andThisConfigToo.json",
    "!/mods/andAllTheseMods-*.jar",
    "!/mods/server-*.jar"
  ],
  "allowEditsInFiles": [
    "/options.txt",
    "!/config/excludeThisFile"
  ],
```

Try it again

**Comment by TeQTabanca** [comment]
> ![image](https://private-user-images.githubusercontent.com/55131959/386872503-2dc22ea7-95f9-49e6-a375-aafb8c5251d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODYwNzAsIm5iZiI6MTczMTc4NTc3MCwicGF0aCI6Ii81NTEzMTk1OS8zODY4NzI1MDMtMmRjMjJlYTctOTVmOS00OWU2LWEzNzUtYWFmYjhjNTI1MWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE5MzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOWZiOGU0YWRmZTYxNjhiODY5ZWVhZTIwZDNiZDcxNTQwMWRlNmZmOGRhYWEwMDYwZWUzNWIxMjNmMmExMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AIlW57CC5fcWvnQM9nrcv377PuJyhq4rqhZjw5-5x6Q) You don't need the folder, delete it, in this folder there is the config file, that file overwrite the config files again
> 
> [automodpack-server.json](https://github.com/user-attachments/files/17787717/automodpack-server.json) Use this Automodpack setting, it sync the complet config folder from server config
> 
> ```
>   "syncedFiles": [
>     "/mods/*.jar",
>     "/config/*",
>     "!/mods/iDontWantThisModInModpack.jar",
>     "!/config/andThisConfigToo.json",
>     "!/mods/andAllTheseMods-*.jar",
>     "!/mods/server-*.jar"
>   ],
>   "allowEditsInFiles": [
>     "/options.txt",
>     "!/config/excludeThisFile"
>   ],
> ```
> 
> Try it again

Synchronization was achieved by adding the "/config/*" text to the "syncedFiles" property. So there is no need to add any .conf file to the main folder. Thanks for your help. It seems like such a setting should be made default when you release the new version.

**Comment by suerion** [comment]
It is not an issue, it is because, you could change all settings for the client to sync, if you do, you could do.

if some other don't need to sync config files, it is okey.

Only for an little looking on other configs, here is mine 
[automodpack-server.json](https://github.com/user-attachments/files/17787778/automodpack-server.json)

i exclude some server sided mods, because a lot of mod devs forget to give the server sided oder client side tag.

only some edits are allowed, because i will give all settings for the modpack.

**Comment by suerion** [comment]
But, it works now for you, you could close your issue, if i or @Skidamek could help you again, add an new issue

and, if you will add only client sided mods, you could use the main folders 
![image](https://github.com/user-attachments/assets/ecc340bc-5318-4568-8a58-f0b9d823f362)

Then it would only sync the files to the client without loading on server side. ;)

**Comment by TeQTabanca** [comment]
> But, it works now for you, you could close your issue, if i or @Skidamek could help you again, add an new issue
> 
> and, if you will add only client sided mods, you could use the main folders ![image](https://private-user-images.githubusercontent.com/55131959/386874294-ecc340bc-5318-4568-8a58-f0b9d823f362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODczMTQsIm5iZiI6MTczMTc4NzAxNCwicGF0aCI6Ii81NTEzMTk1OS8zODY4NzQyOTQtZWNjMzQwYmMtNTMxOC00NTY4LThhNTgtZjBiOWQ4MjNmMzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE5NTY1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNmM3ZjUxMWFhNDEwYTZlY2I4ZTIwNGI4ZWFmNDcyMDI0Zjc2ZjczNjlmOTM2NDU4N2ZhMGI1ZDhiNDE4ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w5_IScmKWCkALYmDay-56hJemQUllgEArBGXTxaFH68)
> 
> Then it would only sync the files to the client without loading on server side. ;)

I'm already adding client-side modes here. Some client-side mods do not work on the server side, but when I put them in the main folder, there is no problem.
