### ISSUE TITLE
Perma "Downloading" Screen

### ISSUE THREAD

**Issue by merkoclerko** [Skidamek/AutoModpack#30]
**Describe the bug**
After following the instructions, my game gets stuck on the initial Downloading screen at 0%

**To Reproduce**
1.  There aren't many steps to reproduce, for me it is getting stuck here mostly out of the box.

**Expected behavior**
I expected this would skip over the Downloading screen as I have the most current version of the modpack as I put it together.  

**Screenshots**
![image](https://user-images.githubusercontent.com/57376573/179046633-b87dd45d-57c1-4d13-8bf1-7d7e0e9fc722.png)
![image](https://user-images.githubusercontent.com/57376573/179047241-8d7f20d2-e179-4286-8831-dafa1956a3c7.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
Minecraft 1.19
AMP is the latest release from 7/12, no version number other than 1.19

**Additional context**
[Hastebin of my config file](https://www.toptal.com/developers/hastebin/ocidobunum.ini)

**Comment by Skidamek** [comment]
Can you send logs (server and client) and file from ./AutoModpack/modpack-link.txt (client) because of security, send it to me on discord Skidam#0001

**Comment by Skidamek** [comment]
Resolved, (for somebody who read this message in the future read readme and open the ports) :D
