### ISSUE TITLE
[Question]: resource packs automatically enabled

### ISSUE THREAD

**Issue by j-tap** [Skidamek/AutoModpack#303]
Hello! 
Thanks for the great mod!
Is there any way I can make the resource packs automatically connect in the right order?
I tried using Paxi but it doesn't seem to work with AutoModpack.
Can you give me some advice on this matter?

**Comment by j-tap** [comment]
I was too hasty with the question, now I have reassembled everything and Paxi works as it should.

**Comment by nagyj2** [comment]
Did you add paxi to the server side `/mods/` folder and then add the `paxi` folder to the files to sync? Or did you set it up as client side in `/audomodpack/host-modpack/main/`? Im trying to get auto loading modpacks working on my server as well
