### ISSUE TITLE
Proxy does not see the mod what to do?

### ISSUE THREAD

**Issue by MarlowTension** [Skidamek/AutoModpack#308]
I uploaded the plugin and mod to the server (except the hub) and nothing helped, maybe I don't understand, I just familiarized myself with the mod and still doesn't want to work, here's the video : https://youtu.be/0vmg1N4fPzY
![image](https://github.com/user-attachments/assets/2a18a16f-9486-4918-b108-be26d82b9078) Server log
![image](https://github.com/user-attachments/assets/b6c224f6-11b8-46d6-aa7a-b0efc28dc3ea) Velocity log
The hub does not write this error (Just in and out)

**Comment by Skidamek** [comment]
Yes currently automodpack does not work with Minecraft proxies. You will need a proxy plugin see #224 
There's velocity plugin in the works, hopefully that's the proxy you are using

**Comment by MarlowTension** [comment]
Dev Builds #378 downloaded, but the mod doesn't work on both client and server

**Comment by MarlowTension** [comment]
https://mclo.gs/oCwzqYV Client
https://mclo.gs/eivny19 Mod Server

**Comment by Skidamek** [comment]
> Yes currently automodpack does not work with Minecraft proxies. You will need a proxy plugin see #224 There's velocity plugin in the works, hopefully that's the proxy you are using

**currently automodpack does not work with Minecraft proxies. You will need a proxy plugin**

It does not work yet
