### ISSUE TITLE
Minecraft Automod not extracting files

### ISSUE THREAD

**Issue by FrogKnite** [Skidamek/AutoModpack#31]
My friend recently added automod to his server so it could update the mods for him, but when I got to it, I have not been able to get it working, as soon as the download is finished when I join the server and it goes to extracting it suspends my minecraft and it stops responding, I've checked if minecraft had both read and write permissions, ran it as administrator, Tried a new instance on curseforge, used just fabric in my minecraft folder, I've checked my network permissions, java install, everything, I cannot find any other reasons for it not be working, when I checked task  manager as it was launching minecraft my computer used 100% of my cpu whenever launching, then evens out, when it crashed it was only using 43% of my cpu, so i dont think its a cpu issue, network issue, it didnt seem to be throtling and again the problem was when extractign the files not downloading.

**Comment by Skidamek** [comment]
oh interesting one, so 1. server is your friend server, 2. you connecting to server not through local network right? Can you send full minecraft log?

**Comment by Skidamek** [comment]
the best will be if you send this to me on discord due to private data like ip
