### ISSUE TITLE
Mod adds itself to delmods.txt

### ISSUE THREAD

**Issue by nppgdi** [Skidamek/AutoModpack#34]
I don't know if it's intentional, but when i'm generating a modpack the mod writes itself to delmods.txt.
Users are unable to update modpack second time because AutoModpack was removed from modpack.

**Screenshot**
![image](https://user-images.githubusercontent.com/48496018/179694604-3c26f317-d140-4e63-ab95-84dc110052b5.png)

 Used version:  Minecraft 1.19, AutoModpack 1.19 2.2.1, Fabric

**Comment by Skidamek** [comment]
lol

**Comment by Skidamek** [comment]
Can you discord? Skidam#0001

**Comment by nppgdi** [comment]
Sure thing
