### ISSUE TITLE
Sync config files

### ISSUE THREAD

**Issue by arthurbambou** [Skidamek/AutoModpack#35]
The config files synchronization seems to be disabled in the code as of today.
If it is indeed disabled/not handled it would be great to see this feature coming back?

**Comment by Skidamek** [comment]
At now there only mods are synced, its a another idea todo! thanks

**Comment by Skidamek** [comment]
Done in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
