### ISSUE TITLE
Change of server IP address will break AutoModpack, AutoModpack attempts to download from old IP

### ISSUE THREAD

**Issue by Sachiru** [Skidamek/AutoModpack#39]
**Describe the bug**
Server previously hosted on x.x.x.x, after the hosting provider has changed IPs and now serves on Y.Y.Y.Y, AutoModpack fails to get the updated modpack on the new server and still attempts to poll old IP.

**To Reproduce**
1. Change Server IP address
2. ???
3. Issue 

**Expected behavior**
AutoModpack should not automatically pull modpack updates, but instead connect to the server first then show a "modpack updated" notification or a notice that there's a new modpack.

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - AutoModpack 2.2.4
 - Minecraft 1.19

**Comment by Skidamek** [comment]
Don't worry about errors that AutoModpack can not been downloaded but just join to server and then you should get new ip that is noticed on server launch on AutoModpack host message

**Comment by Skidamek** [comment]
If it still doesn't work
Check if in the server log after start where is a notification about the modpack host launch, there is a correct ip (the ip you are trying to connect to the server) If not change in the config `host_external_ip` to your correct server ip (without port)

Follow the same process if you have a problem with the local host ip, but to `host_external_ip_for_local_players`

**Comment by Skidamek** [comment]
Any updates?

**Comment by Skidamek** [comment]
closing, if issue will still accurate please reopen issue
