### ISSUE TITLE
Modpack not downloading during preload (1.19)

### ISSUE THREAD

**Issue by DamonFerns** [Skidamek/AutoModpack#45]
**Describe the bug**
The modpack will no longer properly download when starting the game after auto-updating to 2.3.0.
I can see the logs saying it is downloading but even if i leave it for a long time nothing happens, it just gets stuck on preload and doesn't open the game.
If i instead try to download it after starting the game, it downloads quickly.
Can also quickly directly download the modpack from the IP using a browser.

**To Reproduce**
1. Change server modpack (e.g. add a mod)
2. Start game
3. Modpack starts to download but never finishes, so game window never appears

**Expected behavior**
In the previous version of AutoModpack, the modpack would download after pre-loading. 
In this current version the download should be done during pre-loading, then start the game. But this does not happen

**Screenshots**
Minecraft debug log (gets stuck like this)
![automodpack debug log](https://user-images.githubusercontent.com/93787817/183762059-cb87818b-3f87-41b6-a6d9-e8e223bcc516.png)

Server log
![automodpack server log](https://user-images.githubusercontent.com/93787817/183762082-2f06ae85-4d92-4bcb-a264-ab571ed53bd7.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
MInecraft 1.19
AutoModpack 2.3.0

**Comment by Skidamek** [comment]
When it happens try type 
/automodpack modpack-host restart
In the server host

**Comment by SinisterEmber** [comment]
During testing, successful attempts make three get requests to the server, however during pre load it seems to stop after getting the second 200 response from the server. I will look further into this.

**Comment by Skidamek** [comment]
Cool, thanks in advance!

**Comment by Skidamek** [comment]
fixed
