### ISSUE TITLE
Essential Mod incompatibility

### ISSUE THREAD

**Issue by Davithy** [Skidamek/AutoModpack#54]
**Describe the bug**
There seems to be an incompatibility with this mod and the essential mod: https://www.curseforge.com/minecraft/mc-mods/essential-mod
It's not that minecraft won't open, but when automodpack is installed, the essential mod hud does not seem to be accessible.

**To Reproduce**
1. Install both automodpack and the essential mod to your client and modmenu if you would like to confirm proper installation
2. Open minecraft
3. You can see that the essential mod hud isn't visible in the menu screen, even though it is still counted in the mod list

**Expected behavior**
For both Automodpack and Essential to operate together.

**Screenshots**
n/a

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - Using AutoModpack 1.19.x and Essential 1.19.x mod for Minecraft 1.19.x

**Additional context**
This is all surface level checking that I've noticed and was hoping that there would be a way to apply compatibility between the two.

**Comment by Skidamek** [comment]
Fixed in 2.3.3
