### ISSUE TITLE
Auto-Update Doesn't Stop Instance From Running

### ISSUE THREAD

**Issue by IAmSneak** [Skidamek/AutoModpack#55]
When launching the game and having automodpack install its update, the instance of the game continues running and results in the game telling you theres another instance running in that game directory.

1. Install AutoModpack-1.19.x-2.3.0
2. Run the game
3. Close out the automodpack window
4. Try launching minecraft and notice it says there is still an instance of minecraft running in that game directory

Expected behavior:
That instance should be closed automatically

- AutoModpack-1.19.x-2.3.0 updated to AutoModpack-1.19.x-2.3.5
- Clientside

Log:
[2022-08-20-1.log](https://github.com/Skidamek/AutoModpack/files/9387715/2022-08-20-1.log)

**Comment by Skidamek** [comment]
AutoModpack didn't have any window pop-up to selfupdate in 2.3.0 version

**Comment by Skidamek** [comment]
Can't reproduce... can you make video of it or show it through discord?

**Comment by IAmSneak** [comment]
> AutoModpack didn't have any window pop-up to selfupdate in 2.3.0 version

i think it was a dev version between 2.3.1 and 2.3.2 then, this still happens in 2.3.0, 2.3.1, and 2.3.2

Ill contact you on discord to show it so you can ask about anything else that might be useful
