### ISSUE TITLE
Auto modpack update text as boxes

### ISSUE THREAD

**Issue by Davithy** [Skidamek/AutoModpack#56]
**Describe the bug**
Auto modpack updater text has boxes instead of text.

**To Reproduce**
1. You'd need to install both automodpack, fabric api, bclib, and betterend/betternether mods
2. Simply launch minecraft and pay attention to the automodpack updater info.

**Expected behavior**
Of course, I'd expect the intended text. This is just a small nitpick, but something I thought was worth mentioning.

**Screenshots**
![image](https://user-images.githubusercontent.com/105761502/185784447-835de70c-78ed-42ea-90f0-11e9d5fe5091.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - AutoModpack version 2.3.6 for mc 1.19.2, Minecraft 1.19.2

**Additional context**
Truthfully, I thought only BClib and the betterx mods caused this issue, but after removing those 3 mods and reintroducing all 150+ mods back into my mods folder, the issue persisted. There's definitely more than one mod causing this issue, but it'd be a little tedious to dig through the mod list to find out which one causes this problem. Hopefully this helps you figure it out though! It really is just a minor issue.

**Comment by Skidamek** [comment]
Fixed in 2.4.0 by removing auto checking updates on launch
