### ISSUE TITLE
java.net.sockettimeoutexception connect timed out 

### ISSUE THREAD

**Issue by SuperKnux** [Skidamek/AutoModpack#57]
**Describe the bug**

On the latest update of the mod, attempting to update the modpack from the server just returns "Up to date!" even if the modpack isn't actually the same. This is seemingly caused by a Java error on the client's side. "java.net.sockettimeoutexception connect timed out"
**To Reproduce**
1. Create a new modpack, with just FAPI and AutoModpack along with a server set up.
2. Launch the game, and attempt to join the server.
3. No profit D:

**Expected behavior**
The client *should* notice that there's an update and tell you instead of booting you from the server due to a mod missing.

**Screenshots**

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - AutoModpack 2.3.7, 1.18.2

**Additional context**

My client is running a recently installed EndeavourOS. I have 16 gigabytes of RAM, and have an Intel i3-9300H along with an Nvidia Geforce GTX 1050 3GB, if this helps.

**Comment by Skidamek** [comment]
This is rather because the automodpack host on server is overloaded and in the result it couses timeout exception, you can try add more threads to the automodpack config

**Comment by SuperKnux** [comment]
Nope. 6 threads, using bloom.host to host the server too. Can't download the modpack from the site it gives, and it worked fine before so... idk what's going on

**Comment by Skidamek** [comment]
[automodpacks.zip](https://github.com/Skidamek/AutoModpack/files/9392007/automodpacks.zip)
I've changed a bit of automodpack host code, could you try it?

**Comment by Skidamek** [comment]
any updates?

**Comment by Skidamek** [comment]
I hope fixed in 2.3.8

**Comment by Skidamek** [comment]
if problem will be still accouris please reopen the issue

**Comment by SuperKnux** [comment]
Reopening the issue because, despite having switched OSes (to Windows from EndeavourOS,) the modpack can't be downloaded on my side, yet others *can.* Trying to download the modpack from the link given returns a "Took too long to respond" error.

**Comment by SuperKnux** [comment]
Nevermind, just had to add the ip itself to the host_external_ip config property along with a different port, although the different port was probably not needed.
