### ISSUE TITLE
Latest update netty handler issue

### ISSUE THREAD

**Issue by Squeetsquib** [Skidamek/AutoModpack#61]
**Describe the bug**

internal exception: io.netty.handler.codec.decoderexception: net.minecraft.class_151: Non [A-z0-9/,_-] character in path of location: minecraft.soh

**To Reproduce**
1. start server
2. attempt to login to server from client
3. connection lost

**AutoModpack and Minecraft Version you are using (please complete the following information):**

-- 2.41

**Client & Server log**
Log from ./logs/latest.log (If you scared of ip leak, please dm me logs on discord Skidam#8666)

upon request

**Comment by Skidamek** [comment]
log would be very helpful

**Comment by Squeetsquib** [comment]
I'll send to you on discord!

**Comment by Skidamek** [comment]
Fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
