### ISSUE TITLE
Quilt crash

### ISSUE THREAD

**Issue by lostopkk** [Skidamek/AutoModpack#62]
**Describe the bug**
Crash when minecraft initialize

**Client & Server log**
https://mclo.gs/uFFlZSA

**Comment by Toon2400** [comment]
Automodpack loads and initializes without error, and the crash is a rendering issue, are you sure this is the mod that caused your game to crash?

**Comment by lostopkk** [comment]
well I took one by one of the mods I had, even to see the disabled ones in the log... when I put it, it starts when it crashes minecraft

**Comment by lostopkk** [comment]
> Automodpack loads and initializes without error, and the crash is a rendering issue, are you sure this is the mod that caused your game to crash?

camera overhaul that bugged, it is incompatible for some reason, solved!
