### ISSUE TITLE
Modpack not downloading on prelaunch

### ISSUE THREAD

**Issue by IAmSneak** [Skidamek/AutoModpack#63]
modpack doesnt download on prelaunch even when the danger_screen config is set to false (or true, but that seems intentional)

1. update modpack on server
2. client doesnt download modpack on prelaunch, but does when trying to join server

should download on prelaunch

Versions:
 - 2.4.1 for 1.19

**Client & Server log**
I dont have logs of client, but the server doesnt have any interesting info

**Comment by Skidamek** [comment]
Yeah, it changed in latest's updates, now clients' needs to have in AutoModpack config `danger_screen` to false

Then I realized that this is more not too great so, I will change it or at least rollback this to like it was before

**Comment by IAmSneak** [comment]
i agree with rolling back the change, but it also happened when it was set to false

**Comment by Skidamek** [comment]
wait, what does `danger_screen` doesnt work?

**Comment by IAmSneak** [comment]
it worked for 1/5 of the people who tried on my server
