### ISSUE TITLE
Odd netty mod incompatabilities causing 'Connection Refused' 

### ISSUE THREAD

**Issue by BLovegrove** [Skidamek/AutoModpack#69]
**Describe the bug**
Mod is causing multiple errors seemingly related to Netty when added to my server pack. Prevents people from joining the server. The errors themselves all seem to stem from other mods but only appear when the AutoModpack mod is added so I would assume its the real cause.

**To Reproduce**
1. With PolyMC/MultiMC: Add instance and use url provided for non-launcher method.
Without PolyMC/MultiMC: Download the modpack (available [here](http://assets.lamz.org/lamzpack_vf1.18.2.zip)) Sorry no ssl yet but its just an asset dump so should be fine
2. Run modpack
3. Attempt to join my server at 158.140.235.250:25566
4. Edit: Let me know if you end up wanting to jump on my server for testing so I can reset the mods back. Removed AutoModpack for the time being so people can still sue it.

**Expected behavior**
Connects just fine. As it does when I remove AutoModpack

**Screenshots**
![image](https://user-images.githubusercontent.com/32378871/192171786-62f7cd3a-42b4-4bf9-b5bf-62ad511c9b51.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 AutoModpack version 2.4.1 for MC 1.18.2

**Additional context**
Other problems have popped up before too including a weird error the google hivemind doesn't even know about:
"java.lang.IllegalArgumentException: Fluid may not be flowing. " - not a single related result I could find.

**Client & Server log**
[Log file](https://mclo.gs/2H2T7mA)

**Comment by BLovegrove** [comment]
Any updates on this? Or anything I can do to help in the meantime? Not trying to rush, just curious :')

**Comment by Skidamek** [comment]
> Any updates on this? Or anything I can do to help in the meantime? Not trying to rush, just curious :') 

Nothing yet

**Comment by Skidamek** [comment]
> Any updates on this? Or anything I can do to help in the meantime? Not trying to rush, just curious :') 

Nothing yet

**Comment by otowm** [comment]
same problem with 1.19.2

**Comment by Skidamek** [comment]
Fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
