### ISSUE TITLE
Update stalls if a mod contains a bracket in its name

### ISSUE THREAD

**Issue by JLUsr** [Skidamek/AutoModpack#70]
AutoModpack-1.19.x-2.4.1

Basically, if a mod contains a bracket in its name a modpack will get stuck whilst updating.
For reference, when `InventoryHUD-fabric-[1.19.1]+-3.4.2.jar` is placed in the mods folder for an update any client attempting to update will simply remain stuck on the updating screen until they forcefully close the game; however, renaming the file to `InventoryHUD-fabric-1.19.1+-3.4.2.jar` will result in everything working as intended.

Though unnecessary, it might be helpful to include a 'Cancel Download' or 'Cancel Update' button to forcefully return to the main menu for added convenience in the event this or similar issues occur.

**Comment by Skidamek** [comment]
Fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
