### ISSUE TITLE
[GAME BREAKING] - Server vs Client ID conflict.

### ISSUE THREAD

**Issue by IDEDARY** [Skidamek/AutoModpack#72]
When using the autogenerated modpack, the modded item ID's in your world will be different than when using the default way of loading mods.

1. Have an existing modded world created before using automodpack.
2. Use automodpack.
3. If you check your inventory, items in your inventory look different than before. They are swapped with another item from the same mod. That is however only client side issue and they seem to work on server as intended. (Ex. Used to be aetherium pickaxe is now aetherium elytra, but you cannot put it on yourself and it mines blocks as pickaxe.).

However that ID shuffle seems to be consistent after wards. So once it happens, it will not get shuffled again. So the "used to be pickaxe is now elytra" will keep being elytra no matter how many times you restart game and re-generate modpack (I dont know about adding more mods to the modpack, maybe if you add another mod it will get shuffled again?). 
Version - 1.19.2 - 2.4.1

**Comment by IDEDARY** [comment]
Ok, I spend all day debugging it and pinpointing the cause of it. It turned out the cause of this ID shuffle was betternether mod, however not in it's default settings. There is an option in the config to disable spawning of a certain mob alongside of disabling the **EGG OF THAT MOB**. This may seem like an obvious cause now that it is laid out here, but the reason why i overlooked it in the first place is that when using the normal client configs were NOT needed to be synchronized with the server. If you removed some item server side, client was not required to also have it removed. but with Automodpack that is no longer the case. It seems like it is way stricter for this thing. So yeah, I believe it should at least get written on the wiki that you NEED to synchronize item removal also on the client, having it only server side is not enough.

**Comment by Redd56** [comment]
Yeah thats really strange, maybe its what was causing my issues as well
