### ISSUE TITLE
An option to lower the modpack size comparison decimals

### ISSUE THREAD

**Issue by Auxioni** [Skidamek/AutoModpack#76]
**Is your feature request related to a problem? Please describe.**
Every time I launch Minecraft it keeps trying to update, launch after launch. And so, this mod doesn't let me play Minecraft.

**Describe the solution you'd like**
Add an option to the `automodpack.properties` to set the amount of decimals that are checked every time.

**Describe alternatives you've considered**
Adding more filters like `blacklist.txt`. So like for configs, texturepacks, shaderpacks, etc.

**How it looks:**
```
[21:41:46] [main/INFO]: Checking if modpack is up-to-date...
 [21:41:46] [main/INFO]: Current modpack size: 134742067
[21:41:46] [main/INFO]: Latest modpack size: 134742066 
[21:41:46] [main/INFO]: Updating modpack!
```

**Comment by Augustasjau** [comment]
I don't need it to mach the **exact** amount of bites!

**Comment by Skidamek** [comment]
Sorry for troubles, however mod is in remaking process! So this system will be totally different and without this bug. Stay tuned! :)
