### ISSUE TITLE
Crash during update check

### ISSUE THREAD

**Issue by limejet** [Skidamek/AutoModpack#77]
**Describe the bug**  
Sometimes, during the AutoModpack update step, the mod crashes due to `pl.skidam.automodpack.utils.ModrinthAPI.modrinthAPIversion` being NULL.

**To Reproduce**  
1. Launch minecraft
2. wait

**Expected behavior**  
Automodpack should not cause a crash.

**AutoModpack and Minecraft Version**  
 - Minecraft 1.18.2
 - Fabric 0.14.10
 - AutoModpack 2.4.1
 - JRE 17

**Additional context**  
This happens randomly, but affects both client and server. My guess is that it's modrinth rate limiting or similar.

**Client & Server log**  
[Server log](https://pastebin.com/ki7e7xVs) (not very interesting due to partial obfuscation)
[Client log](https://pastebin.com/F4Yq9EWD)

**Comment by Skidamek** [comment]
Fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
