### ISSUE TITLE
Bloom.host VPS Name or service not known

### ISSUE THREAD

**Issue by SuperKnux** [Skidamek/AutoModpack#79]
**Describe the bug**
Even with the VPS' IP put in the config, the modpack server tries to call the VPS' hostname instead of its' actual IP, resulting in it failing.

**To Reproduce**
1. Buy a Bloom.host VPS
2. Setup a Quilt server with AutoModpack on it.
3. Try to launch.

**Expected behavior**
The modpack launches fine, but AutoModpack fails to start the modpack server with a "Name or service not known" error.

**Screenshots**
![image](https://user-images.githubusercontent.com/34802236/206364915-1806d5ca-9719-4130-8580-43dee2a67a3b.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - 1.19.2 Minecraft and the latest version of AM that I installed today.

**Additional context**

**Client & Server log**
Log from ./logs/latest.log (If you scared of ip leak, please dm me logs on discord Skidam#8666)
[latest.log](https://github.com/Skidamek/AutoModpack/files/10182395/latest.log)

**Comment by Skidamek** [comment]
Fixed in 3.0.0 https://github.com/Skidamek/AutoModpack/releases/tag/v3.0.0-beta
