### ISSUE TITLE
Relauncher broken on linux and macs

### ISSUE THREAD

**Issue by Skidamek** [Skidamek/AutoModpack#87]
AutoModpack is currently not able to relaunch the game on UNIX systems.

**Comment by Skidamek** [comment]
There is a way to bypass the issue, you can add the following line to your launcher's JVM arguments:

- On the logs relauncher command, look for the line starting with `-Dfabric.addMods=`. Copy the line with the full path and paste it into your launcher's JVM arguments.

- On **Quilt**, look for the line starting with `-Dloader.addMods=`. Copy the line with the full path and paste it into your launcher's JVM arguments.

**Comment by asdfghjkl403622** [comment]
Hi! I copied the argument with the full path and put it into my jvm arguments and it did not help. 

`-Dfabric.addMods="/home/********/.local/share/PrismLauncher/instances/1.19.2/.minecraft/automodpack/modpacks/**.**.**.**-30037/mods"`

am I doing something wrong?

**Comment by Skidamek** [comment]
no longer needs to be patched as from 3.1.0 it doesn't needs to work
