### ISSUE TITLE
Upon downloading modpack, relaunching says I have missing mods

### ISSUE THREAD

**Issue by KoshOTP** [Skidamek/AutoModpack#88]
**Describe the bug**
When joining the server and downloading the modpack, restarting says I have missing mods, usually libraries and fabric itself even though they are downloaded and present in both mods folder and the modpack folder and also for some reason the deleted mods foler

**To Reproduce**
1. Join server
2. Download modpack
3. Restart

**Expected behavior**
To be able to launch the game

**Screenshots**
![image](https://user-images.githubusercontent.com/30989617/215290153-cbea5c1e-8cb7-4fce-b0b9-6026b4c2ff00.png)

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 -  3.0.0 AM and 1.19.2

**Additional context**

**Client & Server log**
Log from ./logs/latest.log (If you scared of ip leak, please dm me logs on discord Skidam#8666)

**Comment by Skidamek** [comment]
Can you provide mod files which are in normal ./mods/ folder and ./automodpack/modpack/---/mods/?

**Comment by Skidamek** [comment]
You could also try this build https://github.com/Skidamek/AutoModpack/actions/runs/4033360057

**Comment by KoshOTP** [comment]
I'll check with that build later today and get back to you, don't have the logs atm because i've been sorting out curseforge modpacks for friends on the server

here's the current modlist of the server
[modlist.txt](https://github.com/Skidamek/AutoModpack/files/10535209/modlist.txt)

**Comment by Skidamek** [comment]
Sure, could you also send modpack-content.json from automodpack host-modpack folder on server after checking if this build will work? Thanks :)

**Comment by Skidamek** [comment]
Should fix in 3.0.1. If it's still a problem, re-open the isse.
