### ISSUE TITLE
[Question] Why not upload the new versions to modrinth?

### ISSUE THREAD

**Issue by TheAyes** [Skidamek/AutoModpack#89]
I mean you noted that those version are no longer supported, but why not? I would like to use Prism's auto update feature to manage mod updates.

**Comment by Skidamek** [comment]
Why not? Also don't know lol
Why i didn't it yet? I didn't finished the update yet, on github is released beta for testing :)

**Comment by Skidamek** [comment]
yes, you right

**Comment by TheAyes** [comment]
I'm just saying. You do you.
