### ISSUE TITLE
Connection refusal 

### ISSUE THREAD

**Issue by Zalaman** [Skidamek/AutoModpack#91]
**Describe the bug**
The mod recently updated so I've had to update it onto both my client and server. The handshake to the server comes up saying AutoModpack version match! 
But shortly after comes up with 
has disconnected, reason: [AutoModpack] Install/Update modpack to join on the server 

On the client its prompting 
![Resetart](https://user-images.githubusercontent.com/36924120/216167035-38a3998f-9ef9-49d2-819a-f972a73ee65e.png)
No matter how many times you do press the restart or no or close down and restart the client it repeats

**Expected behavior**
Access to the server.

**AutoModpack and Minecraft Version you are using (please complete the following information):**
automodpack-fabric-3.0.1-1.19.2.jar 
 

**Client & Server log**
For safety removed IP with <IPADDRESS>
01.02 19:10:26 [Server] User Authenticator #3/INFO UUID of player DarkZalaman is 85d35736-a7ed-446e-b12c-1530ede76d21
01.02 19:10:26 [Server] Server thread/INFO Sending channel query
01.02 19:10:26 [Server] Netty Epoll Server IO #6/INFO AutoModpack version match!
01.02 19:10:26 [Server] Netty Epoll Server IO #6/INFO Receiving client channels
01.02 19:10:26 [Server] Netty Epoll Server IO #6/INFO Handshake completed successfully
01.02 19:10:34 [Disconnect] User com.mojang.authlib.GameProfile@1123b87a[id=85d35736-a7ed-446e-b12c-1530ede76d21,name=DarkZalaman,properties={textures=[com.mojang.authlib.properties.Property@d5dd442]},legacy=false] (<IPADDRESS>) has disconnected, reason: [AutoModpack] Install/Update modpack to join
01.02 19:11:08 [Server] Server thread/INFO There are 0 of a max of 180 players online:
01.02 19:11:49 [Server] User Authenticator #4/INFO UUID of player DarkZalaman is 85d35736-a7ed-446e-b12c-1530ede76d21
01.02 19:11:49 [Server] Server thread/INFO Sending channel query
01.02 19:11:49 [Server] Netty Epoll Server IO #8/INFO AutoModpack version match!
01.02 19:11:50 [Server] Netty Epoll Server IO #8/INFO Receiving client channels
01.02 19:11:50 [Server] Netty Epoll Server IO #8/INFO Handshake completed successfully
01.02 19:11:58 [Disconnect] User com.mojang.authlib.GameProfile@1ee02e1b[id=85d35736-a7ed-446e-b12c-1530ede76d21,name=DarkZalaman,properties={textures=[com.mojang.authlib.properties.Property@19eed966]},legacy=false] (<IPADDRESS>) has disconnected, reason: [AutoModpack] Install/Update modpack to join
01.02 19:12:02 [Server] Server thread/INFO There are 0 of a max of 180 players online:
01.02 19:12:56 [Server] Server thread/INFO There are 0 of a max of 180 players online:

No client other than the image

**Comment by Skidamek** [comment]
Hey 👋

AutoModpack version match means that AutoModpack as a mod, version match

Download/Update modpack is different check, it is only to check if modpack doesn't have any updates etc.

Looks like modpack don't loading...
Could you send me two last client logs to check if restart command is correct and what's going on after that? You can send that trough discord if you want to
