### ISSUE TITLE
View Changelogs won't scroll

### ISSUE THREAD

**Issue by JLUsr** [Skidamek/AutoModpack#98]
**Describe the bug**
When clicking `View changelogs` in 3.0.3 scrolling with either the mouse wheel or the scroll bar does not seem to be working.

**To Reproduce**
1.Update modpack
2.click `View Changelogs
3.Try scrolling

**Expected behavior**
It should scroll (>_<)

**Screenshots**
N/A

**AutoModpack and Minecraft Version you are using:**
 - Minecraft 1.19.2 | AutoModpack v3.0.3

**Additional context**
Tiny suggestion to add a back button within the `View changelogs`. Took me longer than I would like to admit to realize that the `Escape` key would take me to the previous page. (._.)

**Client & Server log**
N/A

**Comment by Skidamek** [comment]
Fixed in 3.3.0
