### ISSUE TITLE
AutoModPack copying some mods as type "other"

### ISSUE THREAD

**Issue by technobaboo** [Skidamek/AutoModpack#99]
**Describe the bug**
I looked a bit at the code and it seems that some of my mods in the server mods folder do not have the type "mod" so they are copied straight to the .minecraft/mods folder, causing many cascading issues such as all of those mods failing the hash or exists check causing them to try to be updated causing a whole startup loop.

**To Reproduce**
1. Have a quilt server with mods such as Jade, Trinkets, Amethyst Gravity, etc. that don't appear as a mod
2. Download modpack from client
3. Restart, restart again, and again, forever

**Expected behavior**
Any jar in the mods folder ideally should be treated as a mod

**Screenshots**

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 AutoModPack v3.0.3 and Minecraft 1.19.2

**Additional context**
[modpack-content.zip](https://github.com/Skidamek/AutoModpack/files/10715580/modpack-content.zip)
Contains the JSON that has a bunch of mods labeled as "other"

**Client & Server log**
Server: 
[latest.log.zip](https://github.com/Skidamek/AutoModpack/files/10715583/latest.log.zip)
Client:
https://mclo.gs/VVFAUSB

**Comment by technobaboo** [comment]
aha, I think this is it: https://github.com/Skidamek/AutoModpack/blob/92f2d3cebe2577a0789030a58fc9d5706edf7b14/common/src/main/java/pl/skidam/automodpack/modpack/Modpack.java#L174

**Comment by Skidamek** [comment]
well yes you right but why it returns null from modid in first place....

**Comment by technobaboo** [comment]
I'm still not sure tbh, i know that it worked properly by manually setting
all the mods in the json to the right type...

**Comment by TheDeusDeceptor** [comment]
Happened to me, after changing type to mod client wont load them at all...

**Comment by Skidamek** [comment]
> Happened to me, after changing type to mod client wont load them at all...

Are you using 1.19.2, 1.19.1 or 1.19(.0)?

**Comment by TheDeusDeceptor** [comment]
> > Happened to me, after changing type to mod client wont load them at all...
> 
> Are you using 1.19.2, 1.19.1 or 1.19(.0)?

1.19.2

**Comment by Skidamek** [comment]
> > > Happened to me, after changing type to mod client wont load them at all...
> > 
> > 
> > Are you using 1.19.2, 1.19.1 or 1.19(.0)?
> 
> 1.19.2

Great, this should be fixed, so you could try new not yet released build, from github actions https://github.com/Skidamek/AutoModpack/suites/12093344356/artifacts/636825454

**Comment by TheDeusDeceptor** [comment]
> > > > Happened to me, after changing type to mod client wont load them at all...
> > > 
> > > 
> > > Are you using 1.19.2, 1.19.1 or 1.19(.0)?
> > 
> > 
> > 1.19.2
> 
> Great, this should be fixed already. So if you want to try it, get new not yet released build it from github actions https://github.com/Skidamek/AutoModpack/suites/12093344356/artifacts/636825454

sorry for disturbing, I had few Forge mods which caused issues, my apologies (3.0.3 works great with other 100+ mods I have)
anyway, would be nice to have sort of check function if there are forge mods in future, just in case
thanks for help!

**Comment by Skidamek** [comment]
Fixed in 3.1.0 beta (only 1.19.2 at the moment)
